{
    "swagger": "2.0",
    "info": {
        "version": "2.0",
        "title": "Square Connect API",
        "description": "Client library for accessing the Square Connect APIs",
        "termsOfService": "https://connect.squareup.com/tos",
        "contact": {
            "name": "developers@squareup.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        }
    },
    "host": "connect.squareup.com",
    "schemes": [
        "https"
    ],
    "securityDefinitions": {
        "personal_access_token": {
            "type": "apiKey",
            "description": "Access token for accessing a single Square Account",
            "name": "Authorization",
            "in": "header"
        },
        "oauth2": {
            "type": "oauth2",
            "authorizationUrl": "https://connect.squareup.com/oauth2/authorize?<PARAMETERS>",
            "flow": "accessCode",
            "tokenUrl": "https://connect.squareup.com/oauth2/token",
            "scopes": {
                "MERCHANT_PROFILE_READ": "GET endpoints related to a merchant's business and location entities. Almost all Connect API applications need this permission in order to obtain a merchant's location IDs.",
                "PAYMENTS_READ": "GET endpoints related to transactions and refunds.",
                "PAYMENTS_WRITE": " POST, PUT, and DELETE endpoints related to transactions and refunds. E-commerce applications must request this permission.",
                "CUSTOMERS_READ": " GET endpoints related to customer management.",
                "CUSTOMERS_WRITE": "POST, PUT, and DELETE endpoints related to customer management.",
                "SETTLEMENTS_READ": "GET endpoints related to settlements (deposits).",
                "BANK_ACCOUNTS_READ": "GET endpoints related to a merchant's bank accounts.",
                "ITEMS_READ": "GET endpoints related to a merchant's item library.",
                "ITEMS_WRITE": "POST, PUT, and DELETE endpoints related to a merchant's item library.",
                "ORDERS_READ": "GET endpoints related to a merchant's Square online store.",
                "ORDERS_WRITE": "POST, PUT, and DELETE endpoints related to a merchant's Square online store.",
                "EMPLOYEES_READ": "GET endpoints related to employee management.",
                "EMPLOYEES_WRITE": "POST, PUT, and DELETE endpoints related to employee management.",
                "TIMECARDS_READ": "GET endpoints related to employee timecards.",
                "TIMECARDS_WRITE": "POST, PUT, and DELETE endpoints related to employee timecards."
            }
        }
    },
    "paths": {
        "/v1/me": {
            "get": {
                "tags": [
                    "v1BusinessManagement"
                ],
                "summary": "v1RetrieveBusiness",
                "operationId": "v1RetrieveBusiness",
                "description": "Get a business's information.",
                "security": [{
                    "personal_access_token": [],
                    "petstore_auth": ["MERCHANT_PROFILE_READ"]
                }]
            }
        },
        "/v1/me/locations": {
            "get": {
                "tags": [
                    "v1BusinessManagement"
                ],
                "summary": "v1ListLocations",
                "operationId": "v1ListLocations",
                "description": "Provides details for a business's locations, including their IDs.",
                "security": [{
                    "personal_access_token": [],
                    "petstore_auth": ["MERCHANT_PROFILE_READ"]
                }]
            }
        },
        "/v2/locations/{location_id}/transactions": {
            "post": {
                "tags": [
                    "Transaction"
                ],
                "summary": "Charge",
                "operationId": "Charge",
                "description": "Charges a card represented by a token."
            },
            "get": {
                "tags": [
                    "Transaction"
                ],
                "summary": "ListTransactions",
                "operationId": "ListTransactions",
                "description": "Lists transactions for a particular location.\n\nWhen making a request to this endpoint, your request body **must** include either the `cursor` parameter, or it must\ninclude both `begin_time` and `end_time` with an optional `sort_order`."
            }
        },
        "/v2/locations/{location_id}/transactions/{transaction_id}/refund": {
            "post": {
                "tags": [
                    "Refund"
                ],
                "summary": "CreateRefund",
                "operationId": "CreateRefund",
                "description": "Initiates a refund for a previously charged tender."
            }
        },
        "/v2/locations/{location_id}/refunds": {
            "get": {
                "tags": [
                    "Refund"
                ],
                "summary": "ListRefunds",
                "operationId": "ListRefunds",
                "description": "Lists refunds for one of a business\u0027s locations."
            }
        },
        "/v2/locations": {
            "get": {
                "tags": [
                    "Location"
                ],
                "summary": "ListLocations",
                "operationId": "ListLocations",
                "description": "Provides summary information for all of a business\u0027s locations."
            }
        },
        "/v2/customers": {
            "post": {
                "tags": [
                    "Customer"
                ],
                "summary": "CreateCustomer",
                "operationId": "CreateCustomer",
                "description": "Creates a new customer for the business, which can have associated cards on file.",
                "security": [{
                    "personal_access_token": [],
                    "petstore_auth": ["CUSTOMERS_READ"]
                }]
            },
            "get": {
                "tags": [
                    "Customer"
                ],
                "summary": "ListCustomers",
                "operationId": "ListCustomers",
                "description": "Lists a business\u0027s customers."
            }
        },
        "/v2/customers/{customer_id}": {
            "put": {
                "tags": [
                    "Customer"
                ],
                "summary": "UpdateCustomer",
                "operationId": "UpdateCustomer",
                "description": "Updates the details of an existing customer."
            },
            "get": {
                "tags": [
                    "Customer"
                ],
                "summary": "RetrieveCustomer",
                "operationId": "RetrieveCustomer",
                "description": "Returns details for a single customer."
            },
            "delete": {
                "tags": [
                    "Customer"
                ],
                "summary": "DeleteCustomer",
                "operationId": "DeleteCustomer",
                "description": "Deletes a customer from a business."
            }
        },
        "/v2/customers/{customer_id}/cards": {
            "post": {
                "tags": [
                    "Customer.Card"
                ],
                "summary": "CreateCustomerCard",
                "operationId": "CreateCustomerCard",
                "description": "Adds a card on file to an existing customer."
            }
        },
        "/v2/customers/{customer_id}/cards/{card_id}": {
            "delete": {
                "tags": [
                    "Customer.Card"
                ],
                "summary": "DeleteCustomerCard",
                "operationId": "DeleteCustomerCard",
                "description": "Removes a card on file from a customer."
            }
        },
        "/v2/locations/{location_id}/transactions/{transaction_id}/capture": {
            "post": {
                "tags": [
                    "Transaction"
                ],
                "summary": "CaptureTransaction",
                "operationId": "CaptureTransaction",
                "description": "Captures a transaction that was created with the **Charge**\nendpoint with a `delay_capture` value of `true`."
            }
        },
        "/v2/locations/{location_id}/transactions/{transaction_id}/void": {
            "post": {
                "tags": [
                    "Transaction"
                ],
                "summary": "VoidTransaction",
                "operationId": "VoidTransaction",
                "description": "Cancels a transaction that was created with the **Charge**\nendpoint with a `delay_capture` value of `true`."
            }
        },
        "/v2/locations/{location_id}/transactions/{transaction_id}": {
            "get": {
                "tags": [
                    "Transaction"
                ],
                "summary": "RetrieveTransaction",
                "operationId": "RetrieveTransaction",
                "description": "Retrieves details for a single transaction."
            }
        }
    }
}
