{
  "swagger": "2.0",
  "info": {
    "version": "2.0",
    "title": "Square Connect API",
    "description": "Client library for accessing the Square Connect APIs",
    "termsOfService": "https://connect.squareup.com/tos",
    "contact": {
      "name": "Square Developer Platform",
      "email": "developers@squareup.com",
      "url": "https://squareup.com/developers"
    },
    "license": {
      "name": "Apache 2.0",
      "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
    }
  },
  "host": "connect.squareup.com",
  "schemes": [
    "https"
  ],
  "securityDefinitions": {
    "oauth2": {
      "type": "oauth2",
      "authorizationUrl": "https://connect.squareup.com/oauth2/authorize",
      "flow": "accessCode",
      "tokenUrl": "https://connect.squareup.com/oauth2/token",
      "scopes": {
        "MERCHANT_PROFILE_READ": "GET endpoints related to a merchant\u0027s business and location entities. Almost all Connect API applications need this permission in order to obtain a merchant\u0027s location IDs",
        "PAYMENTS_READ": "GET endpoints related to transactions and refunds",
        "PAYMENTS_WRITE": "POST, PUT, and DELETE endpoints related to transactions and refunds. E-commerce applications must request this permission",
        "CUSTOMERS_READ": " GET endpoints related to customer management",
        "CUSTOMERS_WRITE": "POST, PUT, and DELETE endpoints related to customer management",
        "SETTLEMENTS_READ": "GET endpoints related to settlements (deposits)",
        "BANK_ACCOUNTS_READ": "GET endpoints related to a merchant\u0027s bank accounts",
        "ITEMS_READ": "GET endpoints related to a merchant\u0027s item library",
        "ITEMS_WRITE": "POST, PUT, and DELETE endpoints related to a merchant\u0027s item library",
        "ORDERS_READ": "GET endpoints related to a merchant\u0027s orders",
        "ORDERS_WRITE": "POST, PUT, and DELETE endpoints related to a merchant\u0027s orders",
        "EMPLOYEES_READ": "GET endpoints related to employee management",
        "EMPLOYEES_WRITE": "POST, PUT, and DELETE endpoints related to employee management",
        "TIMECARDS_READ": "GET endpoints related to employee timecards",
        "TIMECARDS_WRITE": "POST, PUT, and DELETE endpoints related to employee timecards",
        "PAYMENTS_WRITE_ADDITIONAL_RECIPIENTS": "Allow third party applications to deduct a portion of each transaction amount.",
        "PAYMENTS_WRITE_IN_PERSON": "POST, PUT, and DELETE endpoints. Grants write access to transaction and refunds information.",
        "INVENTORY_READ": "GET endpoints related to a merchant\u0027s inventory",
        "INVENTORY_WRITE": "POST, PUT, and DELETE endpoints related to a merchant\u0027s inventory"
      }
    },
    "oauth2ClientSecret": {
      "type": "apiKey",
      "in": "header",
      "name": "Authorization"
    }
  },
  "paths": {
    "/mobile/authorization-code": {
      "post": {
        "tags": [
          "MobileAuthorization"
        ],
        "summary": "CreateMobileAuthorizationCode",
        "operationId": "CreateMobileAuthorizationCode",
        "description": "Generates code to authorize a mobile application to connect to a Square card reader\n\nAuthorization codes are one-time-use and expire __60 minutes__ after being issued.\n\n__Important:__ The `Authorization` header you provide to this endpoint must have the following format:\n\n```\nAuthorization: Bearer ACCESS_TOKEN\n```\n\nReplace `ACCESS_TOKEN` with a [valid production authorization credential](https://docs.connect.squareup.com/get-started#step-4-understand-the-differe[...]",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "PAYMENTS_WRITE_IN_PERSON"
        ],
        "x-sq-version": "2019-03-13",
        "security": [
          {
            "oauth2": [
              "PAYMENTS_WRITE_IN_PERSON"
            ]
          }
        ]
      }
    },
    "/oauth2/clients/{client_id}/access-token/renew": {
      "post": {
        "tags": [
          "OAuth"
        ],
        "summary": "RenewToken",
        "operationId": "RenewToken",
        "description": "`RenewToken` is deprecated. For information about refreshing OAuth access tokens, see \n[Renew OAuth Token](/authz/oauth/cookbook/oauth-renew).\n\n\nRenews an OAuth access token before it expires.\n\nOAuth access tokens besides your application\u0027s personal access token expire after __30 days__.\nYou can also renew expired tokens within __15 days__ of their expiration.\nYou cannot renew an access token that has been expired for more than 15 days.\nInstead, the associat[...]",
        "x-release-status": "DEPRECATED",
        "x-sq-version": "2019-03-13",
        "security": [
          {
            "oauth2ClientSecret": []
          }
        ]
      }
    },
    "/oauth2/revoke": {
      "post": {
        "tags": [
          "OAuth"
        ],
        "summary": "RevokeToken",
        "operationId": "RevokeToken",
        "description": "Revokes an access token generated with the OAuth flow.\n\nIf an account has more than one OAuth access token for your application, this\nendpoint revokes all of them, regardless of which token you specify. When an\nOAuth access token is revoked, all of the active subscriptions associated\nwith that OAuth token are canceled immediately.\n\n__Important:__ The `Authorization` header for this endpoint must have the\nfollowing format:\n\n```\nAuthorization: Client APPLICATION_[...]",
        "x-release-status": "PUBLIC",
        "x-sq-version": "2019-03-13",
        "security": [
          {
            "oauth2ClientSecret": []
          }
        ]
      }
    },
    "/oauth2/token": {
      "post": {
        "tags": [
          "OAuth"
        ],
        "summary": "ObtainToken",
        "operationId": "ObtainToken",
        "description": "Returns an OAuth access token. \n\nThe endpoint supports distinct methods of obtaining OAuth access tokens. \nApplications specify a method by adding the `grant_type` parameter \nin the request and also provide relevant information. \nFor more information, see [OAuth access token management](/authz/oauth/how-it-works#oauth-access-token-management). \n\n__Note:__ Regardless of the method application specified,\nthe endpoint always returns two items; an OAuth access token a[...]",
        "x-release-status": "PUBLIC",
        "x-sq-version": "2019-03-13",
        "security": []
      }
    },
    "/v1/me": {
      "get": {
        "tags": [
          "V1Locations"
        ],
        "summary": "RetrieveBusiness",
        "operationId": "RetrieveBusiness",
        "description": "Get a business\u0027s information.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "MERCHANT_PROFILE_READ"
        ],
        "x-sq-version": "2019-03-13",
        "security": [
          {
            "oauth2": [
              "MERCHANT_PROFILE_READ"
            ]
          }
        ]
      }
    },
    "/v1/me/employees": {
      "get": {
        "tags": [
          "V1Employees"
        ],
        "summary": "ListEmployees",
        "operationId": "ListEmployees",
        "description": "Provides summary information for all of a business\u0027s employees.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "EMPLOYEES_READ"
        ],
        "x-sq-version": "2019-03-13",
        "security": [
          {
            "oauth2": [
              "EMPLOYEES_READ"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "V1Employees"
        ],
        "summary": "CreateEmployee",
        "operationId": "CreateEmployee",
        "description": " Use the CreateEmployee endpoint to add an employee to a Square\naccount. Employees created with the Connect API have an initial status\nof `INACTIVE`. Inactive employees cannot sign in to Square Point of Sale\nuntil they are activated from the Square Dashboard. Employee status\ncannot be changed with the Connect API.\n\n\u003caside class\u003d\"important\"\u003e\nEmployee entities cannot be deleted. To disable employee profiles,\nset the employee\u0027s status to \u003cc[...]",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "EMPLOYEES_WRITE"
        ],
        "x-sq-version": "2019-03-13",
        "security": [
          {
            "oauth2": [
              "EMPLOYEES_WRITE"
            ]
          }
        ]
      }
    },
    "/v1/me/employees/{employee_id}": {
      "get": {
        "tags": [
          "V1Employees"
        ],
        "summary": "RetrieveEmployee",
        "operationId": "RetrieveEmployee",
        "description": "Provides the details for a single employee.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "EMPLOYEES_READ"
        ],
        "x-sq-version": "2019-03-13",
        "security": [
          {
            "oauth2": [
              "EMPLOYEES_READ"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "V1Employees"
        ],
        "summary": "UpdateEmployee",
        "operationId": "UpdateEmployee",
        "description": "",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "EMPLOYEES_WRITE"
        ],
        "x-sq-version": "2019-03-13",
        "security": [
          {
            "oauth2": [
              "EMPLOYEES_WRITE"
            ]
          }
        ]
      }
    },
    "/v1/me/locations": {
      "get": {
        "tags": [
          "V1Locations"
        ],
        "summary": "ListLocations",
        "operationId": "ListLocations",
        "description": "Provides details for a business\u0027s locations, including their IDs.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "MERCHANT_PROFILE_READ"
        ],
        "x-sq-version": "2019-03-13",
        "security": [
          {
            "oauth2": [
              "MERCHANT_PROFILE_READ"
            ]
          }
        ]
      }
    },
    "/v1/me/roles": {
      "get": {
        "tags": [
          "V1Employees"
        ],
        "summary": "ListEmployeeRoles",
        "operationId": "ListEmployeeRoles",
        "description": "Provides summary information for all of a business\u0027s employee roles.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "EMPLOYEES_READ"
        ],
        "x-sq-version": "2019-03-13",
        "security": [
          {
            "oauth2": [
              "EMPLOYEES_READ"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "V1Employees"
        ],
        "summary": "CreateEmployeeRole",
        "operationId": "CreateEmployeeRole",
        "description": "Creates an employee role you can then assign to employees.\n\nSquare accounts can include any number of roles that can be assigned to\nemployees. These roles define the actions and permissions granted to an\nemployee with that role. For example, an employee with a \"Shift Manager\"\nrole might be able to issue refunds in Square Point of Sale, whereas an\nemployee with a \"Clerk\" role might not.\n\nRoles are assigned with the [V1UpdateEmployee](#endpoint-v1updateemployee)[...]",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "EMPLOYEES_WRITE"
        ],
        "x-sq-version": "2019-03-13",
        "security": [
          {
            "oauth2": [
              "EMPLOYEES_WRITE"
            ]
          }
        ]
      }
    },
    "/v1/me/roles/{role_id}": {
      "get": {
        "tags": [
          "V1Employees"
        ],
        "summary": "RetrieveEmployeeRole",
        "operationId": "RetrieveEmployeeRole",
        "description": "Provides the details for a single employee role.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "EMPLOYEES_READ"
        ],
        "x-sq-version": "2019-03-13",
        "security": [
          {
            "oauth2": [
              "EMPLOYEES_READ"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "V1Employees"
        ],
        "summary": "UpdateEmployeeRole",
        "operationId": "UpdateEmployeeRole",
        "description": "Modifies the details of an employee role.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "EMPLOYEES_WRITE"
        ],
        "x-sq-version": "2019-03-13",
        "security": [
          {
            "oauth2": [
              "EMPLOYEES_WRITE"
            ]
          }
        ]
      }
    },
    "/v1/me/timecards": {
      "get": {
        "tags": [
          "V1Employees"
        ],
        "summary": "ListTimecards",
        "operationId": "ListTimecards",
        "description": "Provides summary information for all of a business\u0027s employee timecards.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "TIMECARDS_READ"
        ],
        "x-sq-version": "2019-03-13",
        "security": [
          {
            "oauth2": [
              "TIMECARDS_READ"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "V1Employees"
        ],
        "summary": "CreateTimecard",
        "operationId": "CreateTimecard",
        "description": "Creates a timecard for an employee and clocks them in with an\n`API_CREATE` event and a `clockin_time` set to the current time unless\nthe request provides a different value. To import timecards from another\nsystem (rather than clocking someone in). Specify the `clockin_time`\nand* `clockout_time` in the request.\n\nTimecards correspond to exactly one shift for a given employee, bounded\nby the `clockin_time` and `clockout_time` fields. An employee is\nconsidered clocked[...]",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "TIMECARDS_WRITE"
        ],
        "x-sq-version": "2019-03-13",
        "security": [
          {
            "oauth2": [
              "TIMECARDS_WRITE"
            ]
          }
        ]
      }
    },
    "/v1/me/timecards/{timecard_id}": {
      "delete": {
        "tags": [
          "V1Employees"
        ],
        "summary": "DeleteTimecard",
        "operationId": "DeleteTimecard",
        "description": "Deletes a timecard. Timecards can also be deleted through the\nSquare Dashboard. Deleted timecards are still accessible through\nConnect API endpoints, but cannot be modified. The `deleted` field of\nthe `Timecard` object indicates whether the timecard has been deleted.\n\n*Note**: By default, deleted timecards appear alongside valid timecards in\nresults returned by the [ListTimecards](#endpoint-v1employees-listtimecards)\nendpoint. To filter deleted timecards, include t[...]",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "TIMECARDS_WRITE"
        ],
        "x-sq-version": "2019-03-13",
        "security": [
          {
            "oauth2": [
              "TIMECARDS_WRITE"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "V1Employees"
        ],
        "summary": "RetrieveTimecard",
        "operationId": "RetrieveTimecard",
        "description": "Provides the details for a single timecard.\n\u003caside\u003e\nOnly approved accounts can manage their employees with Square.\nUnapproved accounts cannot use employee management features with the\nAPI.\n\u003c/aside\u003e",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "TIMECARDS_READ"
        ],
        "x-sq-version": "2019-03-13",
        "security": [
          {
            "oauth2": [
              "TIMECARDS_READ"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "V1Employees"
        ],
        "summary": "UpdateTimecard",
        "operationId": "UpdateTimecard",
        "description": "Modifies the details of a timecard with an `API_EDIT` event for\nthe timecard. Updating an active timecard with a `clockout_time`\nclocks the employee out.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "TIMECARDS_WRITE"
        ],
        "x-sq-version": "2019-03-13",
        "security": [
          {
            "oauth2": [
              "TIMECARDS_WRITE"
            ]
          }
        ]
      }
    },
    "/v1/me/timecards/{timecard_id}/events": {
      "get": {
        "tags": [
          "V1Employees"
        ],
        "summary": "ListTimecardEvents",
        "operationId": "ListTimecardEvents",
        "description": "Provides summary information for all events associated with a\nparticular timecard.\n\n\u003caside\u003e\nOnly approved accounts can manage their employees with Square.\nUnapproved accounts cannot use employee management features with the\nAPI.\n\u003c/aside\u003e",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "TIMECARDS_READ"
        ],
        "x-sq-version": "2019-03-13",
        "security": [
          {
            "oauth2": [
              "TIMECARDS_READ"
            ]
          }
        ]
      }
    },
    "/v1/{location_id}/bank-accounts": {
      "get": {
        "tags": [
          "V1Transactions"
        ],
        "summary": "ListBankAccounts",
        "operationId": "ListBankAccounts",
        "description": "Provides non-confidential details for all of a location\u0027s associated bank accounts. This endpoint does not provide full bank account numbers, and there is no way to obtain a full bank account number with the Connect API.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "BANK_ACCOUNTS_READ"
        ],
        "x-sq-version": "2019-03-13",
        "security": [
          {
            "oauth2": [
              "BANK_ACCOUNTS_READ"
            ]
          }
        ]
      }
    },
    "/v1/{location_id}/bank-accounts/{bank_account_id}": {
      "get": {
        "tags": [
          "V1Transactions"
        ],
        "summary": "RetrieveBankAccount",
        "operationId": "RetrieveBankAccount",
        "description": "Provides non-confidential details for a merchant\u0027s associated bank account. This endpoint does not provide full bank account numbers, and there is no way to obtain a full bank account number with the Connect API.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "BANK_ACCOUNTS_READ"
        ],
        "x-sq-version": "2019-03-13",
        "security": [
          {
            "oauth2": [
              "BANK_ACCOUNTS_READ"
            ]
          }
        ]
      }
    },
    "/v1/{location_id}/cash-drawer-shifts": {
      "get": {
        "tags": [
          "V1Employees"
        ],
        "summary": "ListCashDrawerShifts",
        "operationId": "ListCashDrawerShifts",
        "description": "Provides the details for all of a location\u0027s cash drawer shifts during a date range. The date range you specify cannot exceed 90 days.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "PAYMENTS_READ"
        ],
        "x-sq-version": "2019-03-13",
        "security": [
          {
            "oauth2": [
              "PAYMENTS_READ"
            ]
          }
        ]
      }
    },
    "/v1/{location_id}/cash-drawer-shifts/{shift_id}": {
      "get": {
        "tags": [
          "V1Employees"
        ],
        "summary": "RetrieveCashDrawerShift",
        "operationId": "RetrieveCashDrawerShift",
        "description": "Provides the details for a single cash drawer shift, including all events that occurred during the shift.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "TIMECARDS_READ"
        ],
        "x-sq-version": "2019-03-13",
        "security": [
          {
            "oauth2": [
              "TIMECARDS_READ"
            ]
          }
        ]
      }
    },
    "/v1/{location_id}/categories": {
      "get": {
        "tags": [
          "V1Items"
        ],
        "summary": "ListCategories",
        "operationId": "ListCategories",
        "description": "Lists all of a location\u0027s item categories.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "ITEMS_READ"
        ],
        "x-sq-version": "2019-03-13",
        "security": [
          {
            "oauth2": [
              "ITEMS_READ"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "V1Items"
        ],
        "summary": "CreateCategory",
        "operationId": "CreateCategory",
        "description": "Creates an item category.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "ITEMS_WRITE"
        ],
        "x-sq-version": "2019-03-13",
        "security": [
          {
            "oauth2": [
              "ITEMS_WRITE"
            ]
          }
        ]
      }
    },
    "/v1/{location_id}/categories/{category_id}": {
      "delete": {
        "tags": [
          "V1Items"
        ],
        "summary": "DeleteCategory",
        "operationId": "DeleteCategory",
        "description": "Deletes an existing item category.\n*Note**: DeleteCategory returns nothing on success but Connect SDKs\nmap the empty response to an empty `V1DeleteCategoryRequest` object\nas documented below.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "ITEMS_WRITE"
        ],
        "x-sq-version": "2019-03-13",
        "security": [
          {
            "oauth2": [
              "ITEMS_WRITE"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "V1Items"
        ],
        "summary": "UpdateCategory",
        "operationId": "UpdateCategory",
        "description": "Modifies the details of an existing item category.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "ITEMS_WRITE"
        ],
        "x-sq-version": "2019-03-13",
        "security": [
          {
            "oauth2": [
              "ITEMS_WRITE"
            ]
          }
        ]
      }
    },
    "/v1/{location_id}/discounts": {
      "get": {
        "tags": [
          "V1Items"
        ],
        "summary": "ListDiscounts",
        "operationId": "ListDiscounts",
        "description": "Lists all of a location\u0027s discounts.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "ITEMS_READ"
        ],
        "x-sq-version": "2019-03-13",
        "security": [
          {
            "oauth2": [
              "ITEMS_READ"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "V1Items"
        ],
        "summary": "CreateDiscount",
        "operationId": "CreateDiscount",
        "description": "Creates a discount.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "ITEMS_WRITE"
        ],
        "x-sq-version": "2019-03-13",
        "security": [
          {
            "oauth2": [
              "ITEMS_WRITE"
            ]
          }
        ]
      }
    },
    "/v1/{location_id}/discounts/{discount_id}": {
      "delete": {
        "tags": [
          "V1Items"
        ],
        "summary": "DeleteDiscount",
        "operationId": "DeleteDiscount",
        "description": "Deletes an existing discount.\n*Note**: DeleteDiscount returns nothing on success but Connect SDKs\nmap the empty response to an empty `V1DeleteDiscountRequest` object\nas documented below.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "ITEMS_WRITE"
        ],
        "x-sq-version": "2019-03-13",
        "security": [
          {
            "oauth2": [
              "ITEMS_WRITE"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "V1Items"
        ],
        "summary": "UpdateDiscount",
        "operationId": "UpdateDiscount",
        "description": "Modifies the details of an existing discount.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "ITEMS_WRITE"
        ],
        "x-sq-version": "2019-03-13",
        "security": [
          {
            "oauth2": [
              "ITEMS_WRITE"
            ]
          }
        ]
      }
    },
    "/v1/{location_id}/fees": {
      "get": {
        "tags": [
          "V1Items"
        ],
        "summary": "ListFees",
        "operationId": "ListFees",
        "description": "Lists all of a location\u0027s fees (taxes).",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "ITEMS_READ"
        ],
        "x-sq-version": "2019-03-13",
        "security": [
          {
            "oauth2": [
              "ITEMS_READ"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "V1Items"
        ],
        "summary": "CreateFee",
        "operationId": "CreateFee",
        "description": "Creates a fee (tax).",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "ITEMS_WRITE"
        ],
        "x-sq-version": "2019-03-13",
        "security": [
          {
            "oauth2": [
              "ITEMS_WRITE"
            ]
          }
        ]
      }
    },
    "/v1/{location_id}/fees/{fee_id}": {
      "delete": {
        "tags": [
          "V1Items"
        ],
        "summary": "DeleteFee",
        "operationId": "DeleteFee",
        "description": "Deletes an existing fee (tax).\n*Note**: DeleteFee returns nothing on success but Connect SDKs\nmap the empty response to an empty `V1DeleteFeeRequest` object\nas documented below.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "ITEMS_WRITE"
        ],
        "x-sq-version": "2019-03-13",
        "security": [
          {
            "oauth2": [
              "ITEMS_WRITE"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "V1Items"
        ],
        "summary": "UpdateFee",
        "operationId": "UpdateFee",
        "description": "Modifies the details of an existing fee (tax).",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "ITEMS_WRITE"
        ],
        "x-sq-version": "2019-03-13",
        "security": [
          {
            "oauth2": [
              "ITEMS_WRITE"
            ]
          }
        ]
      }
    },
    "/v1/{location_id}/inventory": {
      "get": {
        "tags": [
          "V1Items"
        ],
        "summary": "ListInventory",
        "operationId": "ListInventory",
        "description": "Provides inventory information for all of a merchant\u0027s inventory-enabled item variations.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "ITEMS_READ"
        ],
        "x-sq-version": "2019-03-13",
        "security": [
          {
            "oauth2": [
              "ITEMS_READ"
            ]
          }
        ]
      }
    },
    "/v1/{location_id}/inventory/{variation_id}": {
      "post": {
        "tags": [
          "V1Items"
        ],
        "summary": "AdjustInventory",
        "operationId": "AdjustInventory",
        "description": "Adjusts an item variation\u0027s current available inventory.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "ITEMS_WRITE"
        ],
        "x-sq-version": "2019-03-13",
        "security": [
          {
            "oauth2": [
              "ITEMS_WRITE"
            ]
          }
        ]
      }
    },
    "/v1/{location_id}/items": {
      "get": {
        "tags": [
          "V1Items"
        ],
        "summary": "ListItems",
        "operationId": "ListItems",
        "description": "Provides summary information for all of a location\u0027s items.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "ITEMS_READ"
        ],
        "x-sq-version": "2019-03-13",
        "security": [
          {
            "oauth2": [
              "ITEMS_READ"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "V1Items"
        ],
        "summary": "CreateItem",
        "operationId": "CreateItem",
        "description": "Creates an item and at least one variation for it. Item-related\nentities include fields you can use to associate them with entities in a\nnon-Square system.\n\nWhen you create an item-related entity, you can optionally specify its\n`id`. This value must be unique among all IDs ever specified for the\naccount, including those specified by other applications. You can never\nreuse an entity ID. If you do not specify an ID, Square generates one\nfor the entity.\n\nItem varia[...]",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "ITEMS_WRITE"
        ],
        "x-sq-version": "2019-03-13",
        "security": [
          {
            "oauth2": [
              "ITEMS_WRITE"
            ]
          }
        ]
      }
    },
    "/v1/{location_id}/items/{item_id}": {
      "delete": {
        "tags": [
          "V1Items"
        ],
        "summary": "DeleteItem",
        "operationId": "DeleteItem",
        "description": "Deletes an existing item and all item variations associated with it.\n*Note**: DeleteItem returns nothing on success but Connect SDKs\nmap the empty response to an empty `V1DeleteItemRequest` object\nas documented below.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "ITEMS_WRITE"
        ],
        "x-sq-version": "2019-03-13",
        "security": [
          {
            "oauth2": [
              "ITEMS_WRITE"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "V1Items"
        ],
        "summary": "RetrieveItem",
        "operationId": "RetrieveItem",
        "description": "Provides the details for a single item, including associated modifier lists and fees.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "ITEMS_READ"
        ],
        "x-sq-version": "2019-03-13",
        "security": [
          {
            "oauth2": [
              "ITEMS_READ"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "V1Items"
        ],
        "summary": "UpdateItem",
        "operationId": "UpdateItem",
        "description": "Modifies the core details of an existing item.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "ITEMS_WRITE"
        ],
        "x-sq-version": "2019-03-13",
        "security": [
          {
            "oauth2": [
              "ITEMS_WRITE"
            ]
          }
        ]
      }
    },
    "/v1/{location_id}/items/{item_id}/fees/{fee_id}": {
      "delete": {
        "tags": [
          "V1Items"
        ],
        "summary": "RemoveFee",
        "operationId": "RemoveFee",
        "description": "Removes a fee assocation from an item, meaning the fee is no longer automatically applied to the item in Square Register.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "ITEMS_WRITE"
        ],
        "x-sq-version": "2019-03-13",
        "security": [
          {
            "oauth2": [
              "ITEMS_WRITE"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "V1Items"
        ],
        "summary": "ApplyFee",
        "operationId": "ApplyFee",
        "description": "Associates a fee with an item, meaning the fee is automatically applied to the item in Square Register.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "ITEMS_WRITE"
        ],
        "x-sq-version": "2019-03-13",
        "security": [
          {
            "oauth2": [
              "ITEMS_WRITE"
            ]
          }
        ]
      }
    },
    "/v1/{location_id}/items/{item_id}/modifier-lists/{modifier_list_id}": {
      "delete": {
        "tags": [
          "V1Items"
        ],
        "summary": "RemoveModifierList",
        "operationId": "RemoveModifierList",
        "description": "Removes a modifier list association from an item, meaning modifier options from the list can no longer be applied to the item.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "ITEMS_WRITE"
        ],
        "x-sq-version": "2019-03-13",
        "security": [
          {
            "oauth2": [
              "ITEMS_WRITE"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "V1Items"
        ],
        "summary": "ApplyModifierList",
        "operationId": "ApplyModifierList",
        "description": "Associates a modifier list with an item, meaning modifier options from the list can be applied to the item.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "ITEMS_WRITE"
        ],
        "x-sq-version": "2019-03-13",
        "security": [
          {
            "oauth2": [
              "ITEMS_WRITE"
            ]
          }
        ]
      }
    },
    "/v1/{location_id}/items/{item_id}/variations": {
      "post": {
        "tags": [
          "V1Items"
        ],
        "summary": "CreateVariation",
        "operationId": "CreateVariation",
        "description": "Creates an item variation for an existing item.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "ITEMS_WRITE"
        ],
        "x-sq-version": "2019-03-13",
        "security": [
          {
            "oauth2": [
              "ITEMS_WRITE"
            ]
          }
        ]
      }
    },
    "/v1/{location_id}/items/{item_id}/variations/{variation_id}": {
      "delete": {
        "tags": [
          "V1Items"
        ],
        "summary": "DeleteVariation",
        "operationId": "DeleteVariation",
        "description": "Deletes an existing item variation from an item.\n*Note**: DeleteVariation returns nothing on success but Connect SDKs\nmap the empty response to an empty `V1DeleteVariationRequest` object\nas documented below.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "ITEMS_WRITE"
        ],
        "x-sq-version": "2019-03-13",
        "security": [
          {
            "oauth2": [
              "ITEMS_WRITE"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "V1Items"
        ],
        "summary": "UpdateVariation",
        "operationId": "UpdateVariation",
        "description": "Modifies the details of an existing item variation.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "ITEMS_WRITE"
        ],
        "x-sq-version": "2019-03-13",
        "security": [
          {
            "oauth2": [
              "ITEMS_WRITE"
            ]
          }
        ]
      }
    },
    "/v1/{location_id}/modifier-lists": {
      "get": {
        "tags": [
          "V1Items"
        ],
        "summary": "ListModifierLists",
        "operationId": "ListModifierLists",
        "description": "Lists all of a location\u0027s modifier lists.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "ITEMS_READ"
        ],
        "x-sq-version": "2019-03-13",
        "security": [
          {
            "oauth2": [
              "ITEMS_READ"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "V1Items"
        ],
        "summary": "CreateModifierList",
        "operationId": "CreateModifierList",
        "description": "Creates an item modifier list and at least one modifier option for it.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "ITEMS_WRITE"
        ],
        "x-sq-version": "2019-03-13",
        "security": [
          {
            "oauth2": [
              "ITEMS_WRITE"
            ]
          }
        ]
      }
    },
    "/v1/{location_id}/modifier-lists/{modifier_list_id}": {
      "delete": {
        "tags": [
          "V1Items"
        ],
        "summary": "DeleteModifierList",
        "operationId": "DeleteModifierList",
        "description": "Deletes an existing item modifier list and all modifier options\nassociated with it.\n*Note**: DeleteModifierList returns nothing on success but Connect SDKs\nmap the empty response to an empty `V1DeleteModifierListRequest` object\nas documented below.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "ITEMS_WRITE"
        ],
        "x-sq-version": "2019-03-13",
        "security": [
          {
            "oauth2": [
              "ITEMS_WRITE"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "V1Items"
        ],
        "summary": "RetrieveModifierList",
        "operationId": "RetrieveModifierList",
        "description": "Provides the details for a single modifier list.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "ITEMS_READ"
        ],
        "x-sq-version": "2019-03-13",
        "security": [
          {
            "oauth2": [
              "ITEMS_READ"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "V1Items"
        ],
        "summary": "UpdateModifierList",
        "operationId": "UpdateModifierList",
        "description": "Modifies the details of an existing item modifier list.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "ITEMS_WRITE"
        ],
        "x-sq-version": "2019-03-13",
        "security": [
          {
            "oauth2": [
              "ITEMS_WRITE"
            ]
          }
        ]
      }
    },
    "/v1/{location_id}/modifier-lists/{modifier_list_id}/modifier-options": {
      "post": {
        "tags": [
          "V1Items"
        ],
        "summary": "CreateModifierOption",
        "operationId": "CreateModifierOption",
        "description": "Creates an item modifier option and adds it to a modifier list.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "ITEMS_WRITE"
        ],
        "x-sq-version": "2019-03-13",
        "security": [
          {
            "oauth2": [
              "ITEMS_WRITE"
            ]
          }
        ]
      }
    },
    "/v1/{location_id}/modifier-lists/{modifier_list_id}/modifier-options/{modifier_option_id}": {
      "delete": {
        "tags": [
          "V1Items"
        ],
        "summary": "DeleteModifierOption",
        "operationId": "DeleteModifierOption",
        "description": "Deletes an existing item modifier option from a modifier list.\n*Note**: DeleteModifierOption returns nothing on success but Connect SDKs\nmap the empty response to an empty `V1DeleteModifierOptionRequest` object\nas documented below.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "ITEMS_WRITE"
        ],
        "x-sq-version": "2019-03-13",
        "security": [
          {
            "oauth2": [
              "ITEMS_WRITE"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "V1Items"
        ],
        "summary": "UpdateModifierOption",
        "operationId": "UpdateModifierOption",
        "description": "Modifies the details of an existing item modifier option.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "ITEMS_WRITE"
        ],
        "x-sq-version": "2019-03-13",
        "security": [
          {
            "oauth2": [
              "ITEMS_WRITE"
            ]
          }
        ]
      }
    },
    "/v1/{location_id}/orders": {
      "get": {
        "tags": [
          "V1Transactions"
        ],
        "summary": "ListOrders",
        "operationId": "ListOrders",
        "description": "Provides summary information for a merchant\u0027s online store orders.",
        "x-release-status": "PUBLIC",
        "x-visibility": "SDK_ONLY",
        "x-oauthpermissions": [
          "ORDERS_READ"
        ],
        "x-sq-version": "2019-03-13",
        "security": [
          {
            "oauth2": [
              "ORDERS_READ"
            ]
          }
        ]
      }
    },
    "/v1/{location_id}/orders/{order_id}": {
      "get": {
        "tags": [
          "V1Transactions"
        ],
        "summary": "RetrieveOrder",
        "operationId": "RetrieveOrder",
        "description": "Provides comprehensive information for a single online store order, including the order\u0027s history.",
        "x-release-status": "PUBLIC",
        "x-visibility": "SDK_ONLY",
        "x-oauthpermissions": [
          "ORDERS_READ"
        ],
        "x-sq-version": "2019-03-13",
        "security": [
          {
            "oauth2": [
              "ORDERS_READ"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "V1Transactions"
        ],
        "summary": "UpdateOrder",
        "operationId": "UpdateOrder",
        "description": "Updates the details of an online store order. Every update you perform on an order corresponds to one of three actions:",
        "x-release-status": "PUBLIC",
        "x-visibility": "SDK_ONLY",
        "x-oauthpermissions": [
          "ORDERS_WRITE"
        ],
        "x-sq-version": "2019-03-13",
        "security": [
          {
            "oauth2": [
              "ORDERS_WRITE"
            ]
          }
        ]
      }
    },
    "/v1/{location_id}/pages": {
      "get": {
        "tags": [
          "V1Items"
        ],
        "summary": "ListPages",
        "operationId": "ListPages",
        "description": "Lists all of a location\u0027s Favorites pages in Square Register.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "ITEMS_READ"
        ],
        "x-sq-version": "2019-03-13",
        "security": [
          {
            "oauth2": [
              "ITEMS_READ"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "V1Items"
        ],
        "summary": "CreatePage",
        "operationId": "CreatePage",
        "description": "Creates a Favorites page in Square Register.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "ITEMS_WRITE"
        ],
        "x-sq-version": "2019-03-13",
        "security": [
          {
            "oauth2": [
              "ITEMS_WRITE"
            ]
          }
        ]
      }
    },
    "/v1/{location_id}/pages/{page_id}": {
      "delete": {
        "tags": [
          "V1Items"
        ],
        "summary": "DeletePage",
        "operationId": "DeletePage",
        "description": "Deletes an existing Favorites page and all of its cells.\n*Note**: DeletePage returns nothing on success but Connect SDKs\nmap the empty response to an empty `V1DeletePageRequest` object\nas documented below.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "ITEMS_WRITE"
        ],
        "x-sq-version": "2019-03-13",
        "security": [
          {
            "oauth2": [
              "ITEMS_WRITE"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "V1Items"
        ],
        "summary": "UpdatePage",
        "operationId": "UpdatePage",
        "description": "Modifies the details of a Favorites page in Square Register.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "ITEMS_WRITE"
        ],
        "x-sq-version": "2019-03-13",
        "security": [
          {
            "oauth2": [
              "ITEMS_WRITE"
            ]
          }
        ]
      }
    },
    "/v1/{location_id}/pages/{page_id}/cells": {
      "delete": {
        "tags": [
          "V1Items"
        ],
        "summary": "DeletePageCell",
        "operationId": "DeletePageCell",
        "description": "Deletes a cell from a Favorites page in Square Register.\n*Note**: DeletePageCell returns nothing on success but Connect SDKs\nmap the empty response to an empty `V1DeletePageCellRequest` object\nas documented below.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "ITEMS_WRITE"
        ],
        "x-sq-version": "2019-03-13",
        "security": [
          {
            "oauth2": [
              "ITEMS_WRITE"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "V1Items"
        ],
        "summary": "UpdatePageCell",
        "operationId": "UpdatePageCell",
        "description": "Modifies a cell of a Favorites page in Square Register.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "ITEMS_WRITE"
        ],
        "x-sq-version": "2019-03-13",
        "security": [
          {
            "oauth2": [
              "ITEMS_WRITE"
            ]
          }
        ]
      }
    },
    "/v1/{location_id}/payments": {
      "get": {
        "tags": [
          "V1Transactions"
        ],
        "summary": "ListPayments",
        "operationId": "ListPayments",
        "description": "Provides summary information for all payments taken for a given\nSquare account during a date range. Date ranges cannot exceed 1 year in\nlength. See Date ranges for details of inclusive and exclusive dates.\n\n*Note**: Details for payments processed with Square Point of Sale while\nin offline mode may not be transmitted to Square for up to 72 hours.\nOffline payments have a `created_at` value that reflects the time the\npayment was originally processed, not the time it w[...]",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "PAYMENTS_READ"
        ],
        "x-sq-version": "2019-03-13",
        "security": [
          {
            "oauth2": [
              "PAYMENTS_READ"
            ]
          }
        ]
      }
    },
    "/v1/{location_id}/payments/{payment_id}": {
      "get": {
        "tags": [
          "V1Transactions"
        ],
        "summary": "RetrievePayment",
        "operationId": "RetrievePayment",
        "description": "Provides comprehensive information for a single payment.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "PAYMENTS_READ"
        ],
        "x-sq-version": "2019-03-13",
        "security": [
          {
            "oauth2": [
              "PAYMENTS_READ"
            ]
          }
        ]
      }
    },
    "/v1/{location_id}/refunds": {
      "get": {
        "tags": [
          "V1Transactions"
        ],
        "summary": "ListRefunds",
        "operationId": "ListRefunds",
        "description": "Provides the details for all refunds initiated by a merchant or any of the merchant\u0027s mobile staff during a date range. Date ranges cannot exceed one year in length.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "PAYMENTS_READ"
        ],
        "x-sq-version": "2019-03-13",
        "security": [
          {
            "oauth2": [
              "PAYMENTS_READ"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "V1Transactions"
        ],
        "summary": "CreateRefund",
        "operationId": "CreateRefund",
        "description": "Issues a refund for a previously processed payment. You must issue\na refund within 60 days of the associated payment.\n\nYou cannot issue a partial refund for a split tender payment. You must\ninstead issue a full or partial refund for a particular tender, by\nproviding the applicable tender id to the V1CreateRefund endpoint.\nIssuing a full refund for a split tender payment refunds all tenders\nassociated with the payment.\n\nIssuing a refund for a card payment is not r[...]",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "PAYMENTS_WRITE"
        ],
        "x-sq-version": "2019-03-13",
        "security": [
          {
            "oauth2": [
              "PAYMENTS_WRITE"
            ]
          }
        ]
      }
    },
    "/v1/{location_id}/settlements": {
      "get": {
        "tags": [
          "V1Transactions"
        ],
        "summary": "ListSettlements",
        "operationId": "ListSettlements",
        "description": "Provides summary information for all deposits and withdrawals\ninitiated by Square to a linked bank account during a date range. Date\nranges cannot exceed one year in length.\n\n*Note**: the ListSettlements endpoint does not provide entry\ninformation.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "SETTLEMENTS_READ"
        ],
        "x-sq-version": "2019-03-13",
        "security": [
          {
            "oauth2": [
              "SETTLEMENTS_READ"
            ]
          }
        ]
      }
    },
    "/v1/{location_id}/settlements/{settlement_id}": {
      "get": {
        "tags": [
          "V1Transactions"
        ],
        "summary": "RetrieveSettlement",
        "operationId": "RetrieveSettlement",
        "description": "Provides comprehensive information for a single settlement.\n\nThe returned `Settlement` objects include an `entries` field that lists\nthe transactions that contribute to the settlement total. Most\nsettlement entries correspond to a payment payout, but settlement\nentries are also generated for less common events, like refunds, manual\nadjustments, or chargeback holds.\n\nSquare initiates its regular deposits as indicated in the\n[Deposit Options with Square](https://sq[...]",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "SETTLEMENTS_READ"
        ],
        "x-sq-version": "2019-03-13",
        "security": [
          {
            "oauth2": [
              "SETTLEMENTS_READ"
            ]
          }
        ]
      }
    },
    "/v2/apple-pay/domains": {
      "post": {
        "tags": [
          "ApplePay"
        ],
        "summary": "RegisterDomain",
        "operationId": "RegisterDomain",
        "description": "Activates a domain for use with Web Apple Pay and Square. A validation\nwill be performed on this domain by Apple to ensure is it properly set up as\nan Apple Pay enabled domain.\n\nThis endpoint provides an easy way for platform developers to bulk activate\nWeb Apple Pay with Square for merchants using their platform.\n\nTo learn more about Apple Pay on Web see the Apple Pay section in the\n[Embedding the Square Payment Form](/payments/sqpaymentform/overview) guide.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [],
        "x-sq-version": "2019-03-13",
        "security": [
          {
            "oauth2": []
          }
        ]
      }
    },
    "/v2/catalog/batch-delete": {
      "post": {
        "tags": [
          "Catalog"
        ],
        "summary": "BatchDeleteCatalogObjects",
        "operationId": "BatchDeleteCatalogObjects",
        "description": "Deletes a set of [CatalogItem](#type-catalogitem)s based on the\nprovided list of target IDs and returns a set of successfully deleted IDs in\nthe response. Deletion is a cascading event such that all children of the\ntargeted object are also deleted. For example, deleting a CatalogItem will\nalso delete all of its [CatalogItemVariation](#type-catalogitemvariation)\nchildren.\n\n`BatchDeleteCatalogObjects` succeeds even if only a portion of the targeted\nIDs can be delete[...]",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "ITEMS_WRITE"
        ],
        "x-sq-version": "2019-03-13",
        "security": [
          {
            "oauth2": [
              "ITEMS_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/catalog/batch-retrieve": {
      "post": {
        "tags": [
          "Catalog"
        ],
        "summary": "BatchRetrieveCatalogObjects",
        "operationId": "BatchRetrieveCatalogObjects",
        "description": "Returns a set of objects based on the provided ID.\nEach [CatalogItem](#type-catalogitem) returned in the set includes all of its\nchild information including: all of its\n[CatalogItemVariation](#type-catalogitemvariation) objects, references to\nits [CatalogModifierList](#type-catalogmodifierlist) objects, and the ids of\nany [CatalogTax](#type-catalogtax) objects that apply to it.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "ITEMS_READ"
        ],
        "x-sq-version": "2019-03-13",
        "security": [
          {
            "oauth2": [
              "ITEMS_READ"
            ]
          }
        ]
      }
    },
    "/v2/catalog/batch-upsert": {
      "post": {
        "tags": [
          "Catalog"
        ],
        "summary": "BatchUpsertCatalogObjects",
        "operationId": "BatchUpsertCatalogObjects",
        "description": "Creates or updates up to 10,000 target objects based on the provided\nlist of objects. The target objects are grouped into batches and each batch is\ninserted/updated in an all-or-nothing manner. If an object within a batch is\nmalformed in some way, or violates a database constraint, the entire batch\ncontaining that item will be disregarded. However, other batches in the same\nrequest may still succeed. Each batch may contain up to 1,000 objects, and\nbatches will be pr[...]",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "ITEMS_WRITE"
        ],
        "x-sq-version": "2019-03-13",
        "security": [
          {
            "oauth2": [
              "ITEMS_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/catalog/info": {
      "get": {
        "tags": [
          "Catalog"
        ],
        "summary": "CatalogInfo",
        "operationId": "CatalogInfo",
        "description": "Returns information about the Square Catalog API, such as batch size\nlimits for `BatchUpsertCatalogObjects`.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "ITEMS_READ"
        ],
        "x-sq-version": "2019-03-13",
        "security": [
          {
            "oauth2": [
              "ITEMS_READ"
            ]
          }
        ]
      }
    },
    "/v2/catalog/list": {
      "get": {
        "tags": [
          "Catalog"
        ],
        "summary": "ListCatalog",
        "operationId": "ListCatalog",
        "description": "Returns a list of [CatalogObject](#type-catalogobject)s that includes\nall objects of a set of desired types (for example, all [CatalogItem](#type-catalogitem)\nand [CatalogTax](#type-catalogtax) objects) in the catalog. The types parameter\nis specified as a comma-separated list of valid [CatalogObject](#type-catalogobject) types:\n`ITEM`, `ITEM_VARIATION`, `MODIFIER`, `MODIFIER_LIST`, `CATEGORY`, `DISCOUNT`, `TAX`.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "ITEMS_READ"
        ],
        "x-sq-version": "2019-03-13",
        "security": [
          {
            "oauth2": [
              "ITEMS_READ"
            ]
          }
        ]
      }
    },
    "/v2/catalog/object": {
      "post": {
        "tags": [
          "Catalog"
        ],
        "summary": "UpsertCatalogObject",
        "operationId": "UpsertCatalogObject",
        "description": "Creates or updates the target [CatalogObject](#type-catalogobject).",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "ITEMS_WRITE"
        ],
        "x-sq-version": "2019-03-13",
        "security": [
          {
            "oauth2": [
              "ITEMS_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/catalog/object/{object_id}": {
      "delete": {
        "tags": [
          "Catalog"
        ],
        "summary": "DeleteCatalogObject",
        "operationId": "DeleteCatalogObject",
        "description": "Deletes a single [CatalogObject](#type-catalogobject) based on the\nprovided ID and returns the set of successfully deleted IDs in the response.\nDeletion is a cascading event such that all children of the targeted object\nare also deleted. For example, deleting a [CatalogItem](#type-catalogitem)\nwill also delete all of its\n[CatalogItemVariation](#type-catalogitemvariation) children.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "ITEMS_WRITE"
        ],
        "x-sq-version": "2019-03-13",
        "security": [
          {
            "oauth2": [
              "ITEMS_WRITE"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "Catalog"
        ],
        "summary": "RetrieveCatalogObject",
        "operationId": "RetrieveCatalogObject",
        "description": "Returns a single [CatalogItem](#type-catalogitem) as a\n[CatalogObject](#type-catalogobject) based on the provided ID. The returned\nobject includes all of the relevant [CatalogItem](#type-catalogitem)\ninformation including: [CatalogItemVariation](#type-catalogitemvariation)\nchildren, references to its\n[CatalogModifierList](#type-catalogmodifierlist) objects, and the ids of\nany [CatalogTax](#type-catalogtax) objects that apply to it.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "ITEMS_READ"
        ],
        "x-sq-version": "2019-03-13",
        "security": [
          {
            "oauth2": [
              "ITEMS_READ"
            ]
          }
        ]
      }
    },
    "/v2/catalog/search": {
      "post": {
        "tags": [
          "Catalog"
        ],
        "summary": "SearchCatalogObjects",
        "operationId": "SearchCatalogObjects",
        "description": "Queries the targeted catalog using a variety of query types:\n[CatalogQuerySortedAttribute](#type-catalogquerysortedattribute),\n[CatalogQueryExact](#type-catalogqueryexact),\n[CatalogQueryRange](#type-catalogqueryrange),\n[CatalogQueryText](#type-catalogquerytext),\n[CatalogQueryItemsForTax](#type-catalogqueryitemsfortax), and\n[CatalogQueryItemsForModifierList](#type-catalogqueryitemsformodifierlist).",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "ITEMS_READ"
        ],
        "x-sq-version": "2019-03-13",
        "security": [
          {
            "oauth2": [
              "ITEMS_READ"
            ]
          }
        ]
      }
    },
    "/v2/catalog/update-item-modifier-lists": {
      "post": {
        "tags": [
          "Catalog"
        ],
        "summary": "UpdateItemModifierLists",
        "operationId": "UpdateItemModifierLists",
        "description": "Updates the [CatalogModifierList](#type-catalogmodifierlist) objects\nthat apply to the targeted [CatalogItem](#type-catalogitem) without having\nto perform an upsert on the entire item.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "ITEMS_WRITE"
        ],
        "x-sq-version": "2019-03-13",
        "security": [
          {
            "oauth2": [
              "ITEMS_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/catalog/update-item-taxes": {
      "post": {
        "tags": [
          "Catalog"
        ],
        "summary": "UpdateItemTaxes",
        "operationId": "UpdateItemTaxes",
        "description": "Updates the [CatalogTax](#type-catalogtax) objects that apply to the\ntargeted [CatalogItem](#type-catalogitem) without having to perform an\nupsert on the entire item.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "ITEMS_WRITE"
        ],
        "x-sq-version": "2019-03-13",
        "security": [
          {
            "oauth2": [
              "ITEMS_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/customers": {
      "get": {
        "tags": [
          "Customers"
        ],
        "summary": "ListCustomers",
        "operationId": "ListCustomers",
        "description": "Lists a business\u0027s customers.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "CUSTOMERS_READ"
        ],
        "x-sq-version": "2019-03-13",
        "security": [
          {
            "oauth2": [
              "CUSTOMERS_READ"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Customers"
        ],
        "summary": "CreateCustomer",
        "operationId": "CreateCustomer",
        "description": "Creates a new customer for a business, which can have associated cards on file.\n\nYou must provide __at least one__ of the following values in your request to this\nendpoint:\n\n- `given_name`\n- `family_name`\n- `company_name`\n- `email_address`\n- `phone_number`",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "CUSTOMERS_WRITE"
        ],
        "x-sq-version": "2019-03-13",
        "security": [
          {
            "oauth2": [
              "CUSTOMERS_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/customers/search": {
      "post": {
        "tags": [
          "Customers"
        ],
        "summary": "SearchCustomers",
        "operationId": "SearchCustomers",
        "description": "Searches the customer profiles associated with a Square account.\nCalling SearchCustomers without an explicit query parameter returns all\ncustomer profiles ordered alphabetically based on `given_name` and\n`family_name`.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "CUSTOMERS_READ"
        ],
        "x-sq-version": "2019-03-13",
        "security": [
          {
            "oauth2": [
              "CUSTOMERS_READ"
            ]
          }
        ]
      }
    },
    "/v2/customers/{customer_id}": {
      "delete": {
        "tags": [
          "Customers"
        ],
        "summary": "DeleteCustomer",
        "operationId": "DeleteCustomer",
        "description": "Deletes a customer from a business, along with any linked cards on file. When two profiles\nare merged into a single profile, that profile is assigned a new `customer_id`. You must use the\nnew `customer_id` to delete merged profiles.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "CUSTOMERS_WRITE"
        ],
        "x-sq-version": "2019-03-13",
        "security": [
          {
            "oauth2": [
              "CUSTOMERS_WRITE"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "Customers"
        ],
        "summary": "RetrieveCustomer",
        "operationId": "RetrieveCustomer",
        "description": "Returns details for a single customer.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "CUSTOMERS_READ"
        ],
        "x-sq-version": "2019-03-13",
        "security": [
          {
            "oauth2": [
              "CUSTOMERS_READ"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Customers"
        ],
        "summary": "UpdateCustomer",
        "operationId": "UpdateCustomer",
        "description": "Updates the details of an existing customer. When two profiles are merged\ninto a single profile, that profile is assigned a new `customer_id`. You must use\nthe new `customer_id` to update merged profiles.\n\nYou cannot edit a customer\u0027s cards on file with this endpoint. To make changes\nto a card on file, you must delete the existing card on file with the\n[DeleteCustomerCard](#endpoint-deletecustomercard) endpoint, then create a new one with the\n[CreateCustomerCa[...]",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "CUSTOMERS_WRITE"
        ],
        "x-sq-version": "2019-03-13",
        "security": [
          {
            "oauth2": [
              "CUSTOMERS_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/customers/{customer_id}/cards": {
      "post": {
        "tags": [
          "Customers"
        ],
        "summary": "CreateCustomerCard",
        "operationId": "CreateCustomerCard",
        "description": "Adds a card on file to an existing customer.\n\nAs with charges, calls to `CreateCustomerCard` are idempotent. Multiple\ncalls with the same card nonce return the same card record that was created\nwith the provided nonce during the _first_ call.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "CUSTOMERS_WRITE"
        ],
        "x-sq-version": "2019-03-13",
        "security": [
          {
            "oauth2": [
              "CUSTOMERS_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/customers/{customer_id}/cards/{card_id}": {
      "delete": {
        "tags": [
          "Customers"
        ],
        "summary": "DeleteCustomerCard",
        "operationId": "DeleteCustomerCard",
        "description": "Removes a card on file from a customer.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "CUSTOMERS_WRITE"
        ],
        "x-sq-version": "2019-03-13",
        "security": [
          {
            "oauth2": [
              "CUSTOMERS_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/employees": {
      "get": {
        "tags": [
          "Employees"
        ],
        "summary": "ListEmployees",
        "operationId": "ListEmployees",
        "description": "Gets a list of `Employee` objects for a business.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "EMPLOYEES_READ"
        ],
        "x-sq-version": "2019-03-13",
        "security": [
          {
            "oauth2": [
              "EMPLOYEES_READ"
            ]
          }
        ]
      }
    },
    "/v2/employees/{id}": {
      "get": {
        "tags": [
          "Employees"
        ],
        "summary": "RetrieveEmployee",
        "operationId": "RetrieveEmployee",
        "description": "Gets an `Employee` by Square-assigned employee `ID` (UUID)",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "EMPLOYEES_READ"
        ],
        "x-sq-version": "2019-03-13",
        "security": [
          {
            "oauth2": [
              "EMPLOYEES_READ"
            ]
          }
        ]
      }
    },
    "/v2/inventory/adjustment/{adjustment_id}": {
      "get": {
        "tags": [
          "Inventory"
        ],
        "summary": "RetrieveInventoryAdjustment",
        "operationId": "RetrieveInventoryAdjustment",
        "description": "Returns the [InventoryAdjustment](#type-inventoryadjustment) object\nwith the provided `adjustment_id`.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "INVENTORY_READ"
        ],
        "x-sq-version": "2019-03-13",
        "security": [
          {
            "oauth2": [
              "INVENTORY_READ"
            ]
          }
        ]
      }
    },
    "/v2/inventory/batch-change": {
      "post": {
        "tags": [
          "Inventory"
        ],
        "summary": "BatchChangeInventory",
        "operationId": "BatchChangeInventory",
        "description": "Applies adjustments and counts to the provided item quantities.\n\nOn success: returns the current calculated counts for all objects\nreferenced in the request.\nOn failure: returns a list of related errors.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "INVENTORY_WRITE"
        ],
        "x-sq-version": "2019-03-13",
        "security": [
          {
            "oauth2": [
              "INVENTORY_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/inventory/batch-retrieve-changes": {
      "post": {
        "tags": [
          "Inventory"
        ],
        "summary": "BatchRetrieveInventoryChanges",
        "operationId": "BatchRetrieveInventoryChanges",
        "description": "Returns historical physical counts and adjustments based on the\nprovided filter criteria.\n\nResults are paginated and sorted in ascending order according their\n`occurred_at` timestamp (oldest first).\n\nBatchRetrieveInventoryChanges is a catch-all query endpoint for queries\nthat cannot be handled by other, simpler endpoints.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "INVENTORY_READ"
        ],
        "x-sq-version": "2019-03-13",
        "security": [
          {
            "oauth2": [
              "INVENTORY_READ"
            ]
          }
        ]
      }
    },
    "/v2/inventory/batch-retrieve-counts": {
      "post": {
        "tags": [
          "Inventory"
        ],
        "summary": "BatchRetrieveInventoryCounts",
        "operationId": "BatchRetrieveInventoryCounts",
        "description": "Returns current counts for the provided\n[CatalogObject](#type-catalogobject)s at the requested\n[Location](#type-location)s.\n\nResults are paginated and sorted in descending order according to their\n`calculated_at` timestamp (newest first).\n\nWhen `updated_after` is specified, only counts that have changed since that\ntime (based on the server timestamp for the most recent change) are\nreturned. This allows clients to perform a \"sync\" operation, for example\nin resp[...]",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "INVENTORY_READ"
        ],
        "x-sq-version": "2019-03-13",
        "security": [
          {
            "oauth2": [
              "INVENTORY_READ"
            ]
          }
        ]
      }
    },
    "/v2/inventory/physical-count/{physical_count_id}": {
      "get": {
        "tags": [
          "Inventory"
        ],
        "summary": "RetrieveInventoryPhysicalCount",
        "operationId": "RetrieveInventoryPhysicalCount",
        "description": "Returns the [InventoryPhysicalCount](#type-inventoryphysicalcount)\nobject with the provided `physical_count_id`.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "INVENTORY_READ"
        ],
        "x-sq-version": "2019-03-13",
        "security": [
          {
            "oauth2": [
              "INVENTORY_READ"
            ]
          }
        ]
      }
    },
    "/v2/inventory/{catalog_object_id}": {
      "get": {
        "tags": [
          "Inventory"
        ],
        "summary": "RetrieveInventoryCount",
        "operationId": "RetrieveInventoryCount",
        "description": "Retrieves the current calculated stock count for a given\n[CatalogObject](#type-catalogobject) at a given set of\n[Location](#type-location)s. Responses are paginated and unsorted.\nFor more sophisticated queries, use a batch endpoint.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "INVENTORY_READ"
        ],
        "x-sq-version": "2019-03-13",
        "security": [
          {
            "oauth2": [
              "INVENTORY_READ"
            ]
          }
        ]
      }
    },
    "/v2/inventory/{catalog_object_id}/changes": {
      "get": {
        "tags": [
          "Inventory"
        ],
        "summary": "RetrieveInventoryChanges",
        "operationId": "RetrieveInventoryChanges",
        "description": "Returns a set of physical counts and inventory adjustments for the\nprovided [CatalogObject](#type-catalogobject) at the requested\n[Location](#type-location)s.\n\nResults are paginated and sorted in descending order according to their\n`occurred_at` timestamp (newest first).\n\nThere are no limits on how far back the caller can page. This endpoint is\nuseful when displaying recent changes for a specific item. For more\nsophisticated queries, use a batch endpoint.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "INVENTORY_READ"
        ],
        "x-sq-version": "2019-03-13",
        "security": [
          {
            "oauth2": [
              "INVENTORY_READ"
            ]
          }
        ]
      }
    },
    "/v2/labor/break-types": {
      "get": {
        "tags": [
          "Labor"
        ],
        "summary": "ListBreakTypes",
        "operationId": "ListBreakTypes",
        "description": "Returns a paginated list of `BreakType` instances for a business.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "TIMECARDS_SETTINGS_READ"
        ],
        "x-sq-version": "2019-03-13",
        "security": [
          {
            "oauth2": [
              "TIMECARDS_SETTINGS_READ"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Labor"
        ],
        "summary": "CreateBreakType",
        "operationId": "CreateBreakType",
        "description": "Creates a new `BreakType`. \n\nA `BreakType` is a template for creating `Break` objects. \nYou must provide the following values in your request to this\nendpoint:\n\n- `location_id`\n- `break_name`\n- `expected_duration`\n- `is_paid`\n\nYou can only have 3 `BreakType` instances per location. If you attempt to add a 4th\n`BreakType` for a location, an `INVALID_REQUEST_ERROR` \"Exceeded limit of 3 breaks per location.\"\nis returned.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "TIMECARDS_SETTINGS_WRITE"
        ],
        "x-sq-version": "2019-03-13",
        "security": [
          {
            "oauth2": [
              "TIMECARDS_SETTINGS_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/labor/break-types/{id}": {
      "delete": {
        "tags": [
          "Labor"
        ],
        "summary": "DeleteBreakType",
        "operationId": "DeleteBreakType",
        "description": "Deletes an existing `BreakType`. \n\nA `BreakType` can be deleted even if it is referenced from a `Shift`.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "TIMECARDS_SETTINGS_WRITE"
        ],
        "x-sq-version": "2019-03-13",
        "security": [
          {
            "oauth2": [
              "TIMECARDS_SETTINGS_WRITE"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "Labor"
        ],
        "summary": "GetBreakType",
        "operationId": "GetBreakType",
        "description": "Returns a single `BreakType` specified by id.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "TIMECARDS_SETTINGS_READ"
        ],
        "x-sq-version": "2019-03-13",
        "security": [
          {
            "oauth2": [
              "TIMECARDS_SETTINGS_READ"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Labor"
        ],
        "summary": "UpdateBreakType",
        "operationId": "UpdateBreakType",
        "description": "Updates an existing `BreakType`.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "TIMECARDS_SETTINGS_WRITE",
          "TIMECARDS_SETTINGS_READ"
        ],
        "x-sq-version": "2019-03-13",
        "security": [
          {
            "oauth2": [
              "TIMECARDS_SETTINGS_WRITE",
              "TIMECARDS_SETTINGS_READ"
            ]
          }
        ]
      }
    },
    "/v2/labor/employee-wages": {
      "get": {
        "tags": [
          "Labor"
        ],
        "summary": "ListEmployeeWages",
        "operationId": "ListEmployeeWages",
        "description": "Returns a paginated list of `EmployeeWage` instances for a business.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "EMPLOYEES_READ"
        ],
        "x-sq-version": "2019-03-13",
        "security": [
          {
            "oauth2": [
              "EMPLOYEES_READ"
            ]
          }
        ]
      }
    },
    "/v2/labor/employee-wages/{id}": {
      "get": {
        "tags": [
          "Labor"
        ],
        "summary": "GetEmployeeWage",
        "operationId": "GetEmployeeWage",
        "description": "Returns a single `EmployeeWage` specified by id.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "EMPLOYEES_READ"
        ],
        "x-sq-version": "2019-03-13",
        "security": [
          {
            "oauth2": [
              "EMPLOYEES_READ"
            ]
          }
        ]
      }
    },
    "/v2/labor/shifts": {
      "post": {
        "tags": [
          "Labor"
        ],
        "summary": "CreateShift",
        "operationId": "CreateShift",
        "description": "Creates a new `Shift`. \n\nA `Shift` represents a complete work day for a single employee. \nYou must provide the following values in your request to this\nendpoint:\n\n- `location_id`\n- `employee_id`\n- `start_at`\n\nAn attempt to create a new `Shift` can result in a `BAD_REQUEST` error when:\n- The `status` of the new `Shift` is `OPEN` and the employee has another \nshift with an `OPEN` status. \n- The `start_at` date is in the future\n- the `start_at` or `end_at` over[...]",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "TIMECARDS_WRITE"
        ],
        "x-sq-version": "2019-03-13",
        "security": [
          {
            "oauth2": [
              "TIMECARDS_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/labor/shifts/search": {
      "post": {
        "tags": [
          "Labor"
        ],
        "summary": "SearchShifts",
        "operationId": "SearchShifts",
        "description": "Returns a paginated list of `Shift` records for a business. \nThe list to be returned can be filtered by:\n- Location IDs **and**\n- employee IDs **and**\n- shift status (`OPEN`, `CLOSED`) **and**\n- shift start **and**\n- shift end **and**\n- work day details\n\nThe list can be sorted by:\n- `start_at`\n- `end_at`\n- `created_at`\n- `updated_at`",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "TIMECARDS_READ"
        ],
        "x-sq-version": "2019-03-13",
        "security": [
          {
            "oauth2": [
              "TIMECARDS_READ"
            ]
          }
        ]
      }
    },
    "/v2/labor/shifts/{id}": {
      "delete": {
        "tags": [
          "Labor"
        ],
        "summary": "DeleteShift",
        "operationId": "DeleteShift",
        "description": "Deletes a `Shift`.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "TIMECARDS_SETTINGS_WRITE"
        ],
        "x-sq-version": "2019-03-13",
        "security": [
          {
            "oauth2": [
              "TIMECARDS_SETTINGS_WRITE"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "Labor"
        ],
        "summary": "GetShift",
        "operationId": "GetShift",
        "description": "Returns a single `Shift` specified by id.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "TIMECARDS_READ"
        ],
        "x-sq-version": "2019-03-13",
        "security": [
          {
            "oauth2": [
              "TIMECARDS_READ"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Labor"
        ],
        "summary": "UpdateShift",
        "operationId": "UpdateShift",
        "description": "Updates an existing `Shift`. \n\nWhen adding a `Break` to a `Shift`, any earlier `Breaks` in the `Shift` have \nthe `end_at` property set to a valid RFC-3339 datetime string. \n\nWhen closing a `Shift`, all `Break` instances in the shift must be complete with `end_at`\nset on each `Break`.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "TIMECARDS_WRITE",
          "TIMECARDS_READ"
        ],
        "x-sq-version": "2019-03-13",
        "security": [
          {
            "oauth2": [
              "TIMECARDS_WRITE",
              "TIMECARDS_READ"
            ]
          }
        ]
      }
    },
    "/v2/labor/workweek-configs": {
      "get": {
        "tags": [
          "Labor"
        ],
        "summary": "ListWorkweekConfigs",
        "operationId": "ListWorkweekConfigs",
        "description": "Returns a list of `WorkweekConfig` instances for a business.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "TIMECARDS_SETTINGS_READ"
        ],
        "x-sq-version": "2019-03-13",
        "security": [
          {
            "oauth2": [
              "TIMECARDS_SETTINGS_READ"
            ]
          }
        ]
      }
    },
    "/v2/labor/workweek-configs/{id}": {
      "put": {
        "tags": [
          "Labor"
        ],
        "summary": "UpdateWorkweekConfig",
        "operationId": "UpdateWorkweekConfig",
        "description": "Updates a `WorkweekConfig`.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "TIMECARDS_SETTINGS_WRITE",
          "TIMECARDS_SETTINGS_READ"
        ],
        "x-sq-version": "2019-03-13",
        "security": [
          {
            "oauth2": [
              "TIMECARDS_SETTINGS_WRITE",
              "TIMECARDS_SETTINGS_READ"
            ]
          }
        ]
      }
    },
    "/v2/locations": {
      "get": {
        "tags": [
          "Locations"
        ],
        "summary": "ListLocations",
        "operationId": "ListLocations",
        "description": "Provides the details for all of a business\u0027s locations.\n\nMost other Connect API endpoints have a required `location_id` path parameter.\nThe `id` field of the [`Location`](#type-location) objects returned by this\nendpoint correspond to that `location_id` parameter.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "MERCHANT_PROFILE_READ"
        ],
        "x-sq-version": "2019-03-13",
        "security": [
          {
            "oauth2": [
              "MERCHANT_PROFILE_READ"
            ]
          }
        ]
      }
    },
    "/v2/locations/{location_id}/additional-recipient-receivable-refunds": {
      "get": {
        "tags": [
          "Reporting"
        ],
        "summary": "ListAdditionalRecipientReceivableRefunds",
        "operationId": "ListAdditionalRecipientReceivableRefunds",
        "description": "Returns a list of refunded transactions (across all possible originating locations) relating to monies\ncredited to the provided location ID by another Square account using the `additional_recipients` field in a transaction.\n\nMax results per [page](#paginatingresults): 50",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "PAYMENTS_READ"
        ],
        "x-sq-version": "2019-03-13",
        "security": [
          {
            "oauth2": [
              "PAYMENTS_READ"
            ]
          }
        ]
      }
    },
    "/v2/locations/{location_id}/additional-recipient-receivables": {
      "get": {
        "tags": [
          "Reporting"
        ],
        "summary": "ListAdditionalRecipientReceivables",
        "operationId": "ListAdditionalRecipientReceivables",
        "description": "Returns a list of receivables (across all possible sending locations) representing monies credited\nto the provided location ID by another Square account using the `additional_recipients` field in a transaction.\n\nMax results per [page](#paginatingresults): 50",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "PAYMENTS_READ"
        ],
        "x-sq-version": "2019-03-13",
        "security": [
          {
            "oauth2": [
              "PAYMENTS_READ"
            ]
          }
        ]
      }
    },
    "/v2/locations/{location_id}/checkouts": {
      "post": {
        "tags": [
          "Checkout"
        ],
        "summary": "CreateCheckout",
        "operationId": "CreateCheckout",
        "description": "Links a `checkoutId` to a `checkout_page_url` that customers will\nbe directed to in order to provide their payment information using a\npayment processing workflow hosted on connect.squareup.com.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "PAYMENTS_WRITE",
          "ORDERS_WRITE"
        ],
        "x-sq-version": "2019-03-13",
        "security": [
          {
            "oauth2": [
              "PAYMENTS_WRITE",
              "ORDERS_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/locations/{location_id}/orders": {
      "post": {
        "tags": [
          "Orders"
        ],
        "summary": "CreateOrder",
        "operationId": "CreateOrder",
        "description": "Creates an [Order](#type-order) that can then be referenced as `order_id` in a\nrequest to the [Charge](#endpoint-charge) endpoint. Orders specify products for\npurchase, along with discounts, taxes, and other settings to apply to the purchase.\n\nTo associate a created order with a request to the Charge endpoint, provide the\norder\u0027s `id` in the `order_id` field of your request.\n\nYou cannot modify an order after you create it. If you need to modify an order,\ninst[...]",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "ORDERS_WRITE"
        ],
        "x-sq-version": "2019-03-13",
        "security": [
          {
            "oauth2": [
              "ORDERS_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/locations/{location_id}/orders/batch-retrieve": {
      "post": {
        "tags": [
          "Orders"
        ],
        "summary": "BatchRetrieveOrders",
        "operationId": "BatchRetrieveOrders",
        "description": "Retrieves a set of [Order](#type-order)s by their IDs.\n\nIf a given Order ID does not exist, the ID is ignored instead of generating an error.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "ORDERS_READ"
        ],
        "x-sq-version": "2019-03-13",
        "security": [
          {
            "oauth2": [
              "ORDERS_READ"
            ]
          }
        ]
      }
    },
    "/v2/locations/{location_id}/refunds": {
      "get": {
        "tags": [
          "Transactions"
        ],
        "summary": "ListRefunds",
        "operationId": "ListRefunds",
        "description": "Lists refunds for one of a business\u0027s locations.\n\nIn addition to full or partial tender refunds processed through Square APIs,\nrefunds may result from itemized returns or exchanges through Square\u0027s\nPoint of Sale applications.\n\nRefunds with a `status` of `PENDING` are not currently included in this\nendpoint\u0027s response.\n\nMax results per [page](#paginatingresults): 50",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "PAYMENTS_READ"
        ],
        "x-sq-version": "2019-03-13",
        "security": [
          {
            "oauth2": [
              "PAYMENTS_READ"
            ]
          }
        ]
      }
    },
    "/v2/locations/{location_id}/transactions": {
      "get": {
        "tags": [
          "Transactions"
        ],
        "summary": "ListTransactions",
        "operationId": "ListTransactions",
        "description": "Lists transactions for a particular location.\n\nTransactions include payment information from sales and exchanges and refund\ninformation from returns and exchanges.\n\nMax results per [page](#paginatingresults): 50",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "PAYMENTS_READ"
        ],
        "x-sq-version": "2019-03-13",
        "security": [
          {
            "oauth2": [
              "PAYMENTS_READ"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Transactions"
        ],
        "summary": "Charge",
        "operationId": "Charge",
        "description": "Charges a card represented by a card nonce or a customer\u0027s card on file.\n\nYour request to this endpoint must include _either_:\n\n- A value for the `card_nonce` parameter (to charge a card nonce generated\nwith the `SqPaymentForm`)\n- Values for the `customer_card_id` and `customer_id` parameters (to charge\na customer\u0027s card on file)\n\nIn order for an eCommerce payment to potentially qualify for\n[Square chargeback protection](https://squareup.com/help/artic[...]",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "PAYMENTS_WRITE"
        ],
        "x-sq-version": "2019-03-13",
        "security": [
          {
            "oauth2": [
              "PAYMENTS_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/locations/{location_id}/transactions/{transaction_id}": {
      "get": {
        "tags": [
          "Transactions"
        ],
        "summary": "RetrieveTransaction",
        "operationId": "RetrieveTransaction",
        "description": "Retrieves details for a single transaction.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "PAYMENTS_READ"
        ],
        "x-sq-version": "2019-03-13",
        "security": [
          {
            "oauth2": [
              "PAYMENTS_READ"
            ]
          }
        ]
      }
    },
    "/v2/locations/{location_id}/transactions/{transaction_id}/capture": {
      "post": {
        "tags": [
          "Transactions"
        ],
        "summary": "CaptureTransaction",
        "operationId": "CaptureTransaction",
        "description": "Captures a transaction that was created with the [Charge](#endpoint-charge)\nendpoint with a `delay_capture` value of `true`.\n\nSee [Delayed capture transactions](/payments/transactions/overview#delayed-capture)\nfor more information.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "PAYMENTS_WRITE"
        ],
        "x-sq-version": "2019-03-13",
        "security": [
          {
            "oauth2": [
              "PAYMENTS_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/locations/{location_id}/transactions/{transaction_id}/refund": {
      "post": {
        "tags": [
          "Transactions"
        ],
        "summary": "CreateRefund",
        "operationId": "CreateRefund",
        "description": "Initiates a refund for a previously charged tender.\n\nYou must issue a refund within 120 days of the associated payment. See\n[this article](https://squareup.com/help/us/en/article/5060) for more information\non refund behavior.\n\nNOTE: Card-present transactions with Interac credit cards **cannot be\nrefunded using the Connect API**. Interac transactions must refunded\nin-person (e.g., dipping the card using POS app).",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "PAYMENTS_WRITE"
        ],
        "x-sq-version": "2019-03-13",
        "security": [
          {
            "oauth2": [
              "PAYMENTS_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/locations/{location_id}/transactions/{transaction_id}/void": {
      "post": {
        "tags": [
          "Transactions"
        ],
        "summary": "VoidTransaction",
        "operationId": "VoidTransaction",
        "description": "Cancels a transaction that was created with the [Charge](#endpoint-charge)\nendpoint with a `delay_capture` value of `true`.\n\nSee [Delayed capture transactions](/payments/transactions/overview#delayed-capture)\nfor more information.",
        "x-release-status": "PUBLIC",
        "x-oauthpermissions": [
          "PAYMENTS_WRITE"
        ],
        "x-sq-version": "2019-03-13",
        "security": [
          {
            "oauth2": [
              "PAYMENTS_WRITE"
            ]
          }
        ]
      }
    }
  }
}
