{
  "swagger": "2.0",
  "info": {
    "version": "2.0",
    "title": "Square Connect API",
    "description": "Client library for accessing the Square Connect APIs",
    "termsOfService": "https://connect.squareup.com/tos",
    "contact": {
      "name": "Square Developer Platform",
      "email": "developers@squareup.com",
      "url": "https://squareup.com/developers"
    },
    "license": {
      "name": "Apache 2.0",
      "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
    }
  },
  "host": "connect.squareup.com",
  "schemes": [
    "https"
  ],
  "securityDefinitions": {
    "oauth2": {
      "type": "oauth2",
      "authorizationUrl": "https://connect.squareup.com/oauth2/authorize?\u003cPARAMETERS\u003e",
      "flow": "accessCode",
      "tokenUrl": "https://connect.squareup.com/oauth2/token",
      "scopes": {
        "MERCHANT_PROFILE_READ": "GET endpoints related to a merchant\u0027s business and location entities. Almost all Connect API applications need this permission in order to obtain a merchant\u0027s location IDs",
        "PAYMENTS_READ": "GET endpoints related to transactions and refunds",
        "PAYMENTS_WRITE": "POST, PUT, and DELETE endpoints related to transactions and refunds. E-commerce applications must request this permission",
        "CUSTOMERS_READ": " GET endpoints related to customer management",
        "CUSTOMERS_WRITE": "POST, PUT, and DELETE endpoints related to customer management",
        "SETTLEMENTS_READ": "GET endpoints related to settlements (deposits)",
        "BANK_ACCOUNTS_READ": "GET endpoints related to a merchant\u0027s bank accounts",
        "ITEMS_READ": "GET endpoints related to a merchant\u0027s item library",
        "ITEMS_WRITE": "POST, PUT, and DELETE endpoints related to a merchant\u0027s item library",
        "ORDERS_READ": "GET endpoints related to a merchant\u0027s Square online store.",
        "ORDERS_WRITE": "POST, PUT, and DELETE endpoints related to a merchant\u0027s Square online store",
        "EMPLOYEES_READ": "GET endpoints related to employee management",
        "EMPLOYEES_WRITE": "POST, PUT, and DELETE endpoints related to employee management",
        "TIMECARDS_READ": "GET endpoints related to employee timecards",
        "TIMECARDS_WRITE": "POST, PUT, and DELETE endpoints related to employee timecards"
      }
    }
  },
  "paths": {
    "/v2/locations/{location_id}/transactions": {
      "post": {
        "tags": [
          "Transactions"
        ],
        "summary": "Charge",
        "operationId": "Charge",
        "description": "Charges a card represented by a card nonce or a customer\u0027s card on file.\n\nYour request to this endpoint must include _either_:\n\n- A value for the `card_nonce` parameter (to charge a card nonce generated\nwith the `SqPaymentForm`)\n- Values for the `customer_card_id` and `customer_id` parameters (to charge\na customer\u0027s card on file)\n\nIn order for an e-commerce payment to potentially qualify for\n[Square chargeback protection](https://squareup.com/help/arti[...]",
        "x-oauthpermissions": [
          "PAYMENTS_WRITE"
        ],
        "security": [
          {
            "oauth2": [
              "PAYMENTS_WRITE"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "Transactions"
        ],
        "summary": "ListTransactions",
        "operationId": "ListTransactions",
        "description": "Lists transactions for a particular location.\n\nMax results per [page](#paginatingresults): 50",
        "x-oauthpermissions": [
          "PAYMENTS_READ"
        ],
        "security": [
          {
            "oauth2": [
              "PAYMENTS_READ"
            ]
          }
        ]
      }
    },
    "/v2/locations/{location_id}/transactions/{transaction_id}/refund": {
      "post": {
        "tags": [
          "Transactions"
        ],
        "summary": "CreateRefund",
        "operationId": "CreateRefund",
        "description": "Initiates a refund for a previously charged tender.",
        "x-oauthpermissions": [
          "PAYMENTS_WRITE"
        ],
        "security": [
          {
            "oauth2": [
              "PAYMENTS_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/locations/{location_id}/refunds": {
      "get": {
        "tags": [
          "Transactions"
        ],
        "summary": "ListRefunds",
        "operationId": "ListRefunds",
        "description": "Lists refunds for one of a business\u0027s locations.\n\nRefunds with a `status` of `PENDING` are not currently included in this\nendpoint\u0027s response.\n\nMax results per [page](#paginatingresults): 50",
        "x-oauthpermissions": [
          "PAYMENTS_READ"
        ],
        "security": [
          {
            "oauth2": [
              "PAYMENTS_READ"
            ]
          }
        ]
      }
    },
    "/v2/locations": {
      "get": {
        "tags": [
          "Locations"
        ],
        "summary": "ListLocations",
        "operationId": "ListLocations",
        "description": "Provides the details for all of a business\u0027s locations.\n\nMost other Connect API endpoints have a required `location_id` path parameter.\nThe `id` field of the [`Location`](#type-location) objects returned by this\nendpoint correspond to that `location_id` parameter.",
        "x-oauthpermissions": [
          "MERCHANT_PROFILE_READ"
        ],
        "security": [
          {
            "oauth2": [
              "MERCHANT_PROFILE_READ"
            ]
          }
        ]
      }
    },
    "/v2/customers": {
      "post": {
        "tags": [
          "Customers"
        ],
        "summary": "CreateCustomer",
        "operationId": "CreateCustomer",
        "description": "Creates a new customer for a business, which can have associated cards on file.\n\nYou must provide __at least one__ of the following values in your request to this\nendpoint:\n\n- `given_name`\n- `family_name`\n- `company_name`\n- `email_address`\n- `phone_number`\n\nThis endpoint does not accept an idempotency key. If you accidentally create\na duplicate customer, you can delete it with the\n[DeleteCustomer](#endpoint-deletecustomer) endpoint.",
        "x-oauthpermissions": [
          "CUSTOMERS_WRITE"
        ],
        "security": [
          {
            "oauth2": [
              "CUSTOMERS_WRITE"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "Customers"
        ],
        "summary": "ListCustomers",
        "operationId": "ListCustomers",
        "description": "Lists a business\u0027s customers.",
        "x-oauthpermissions": [
          "CUSTOMERS_READ"
        ],
        "security": [
          {
            "oauth2": [
              "CUSTOMERS_READ"
            ]
          }
        ]
      }
    },
    "/v2/customers/{customer_id}": {
      "put": {
        "tags": [
          "Customers"
        ],
        "summary": "UpdateCustomer",
        "operationId": "UpdateCustomer",
        "description": "Updates the details of an existing customer.\n\nYou cannot edit a customer\u0027s cards on file with this endpoint. To make changes\nto a card on file, you must delete the existing card on file with the\n[DeleteCustomerCard](#endpoint-deletecustomercard) endpoint, then create a new one with the\n[CreateCustomerCard](#endpoint-createcustomercard) endpoint.",
        "x-oauthpermissions": [
          "CUSTOMERS_WRITE"
        ],
        "security": [
          {
            "oauth2": [
              "CUSTOMERS_WRITE"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "Customers"
        ],
        "summary": "RetrieveCustomer",
        "operationId": "RetrieveCustomer",
        "description": "Returns details for a single customer.",
        "x-oauthpermissions": [
          "CUSTOMERS_READ"
        ],
        "security": [
          {
            "oauth2": [
              "CUSTOMERS_READ"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Customers"
        ],
        "summary": "DeleteCustomer",
        "operationId": "DeleteCustomer",
        "description": "Deletes a customer from a business, along with any linked cards on file.",
        "x-oauthpermissions": [
          "CUSTOMERS_WRITE"
        ],
        "security": [
          {
            "oauth2": [
              "CUSTOMERS_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/customers/{customer_id}/cards": {
      "post": {
        "tags": [
          "Customers"
        ],
        "summary": "CreateCustomerCard",
        "operationId": "CreateCustomerCard",
        "description": "Adds a card on file to an existing customer.",
        "x-oauthpermissions": [
          "CUSTOMERS_WRITE"
        ],
        "security": [
          {
            "oauth2": [
              "CUSTOMERS_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/customers/{customer_id}/cards/{card_id}": {
      "delete": {
        "tags": [
          "Customers"
        ],
        "summary": "DeleteCustomerCard",
        "operationId": "DeleteCustomerCard",
        "description": "Removes a card on file from a customer.",
        "x-oauthpermissions": [
          "CUSTOMERS_WRITE"
        ],
        "security": [
          {
            "oauth2": [
              "CUSTOMERS_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/locations/{location_id}/transactions/{transaction_id}/capture": {
      "post": {
        "tags": [
          "Transactions"
        ],
        "summary": "CaptureTransaction",
        "operationId": "CaptureTransaction",
        "description": "Captures a transaction that was created with the [Charge](#endpoint-charge)\nendpoint with a `delay_capture` value of `true`.\n\nSee [Delayed capture transactions](/articles/delayed-capture-transactions/)\nfor more information.",
        "x-oauthpermissions": [
          "PAYMENTS_WRITE"
        ],
        "security": [
          {
            "oauth2": [
              "PAYMENTS_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/locations/{location_id}/transactions/{transaction_id}/void": {
      "post": {
        "tags": [
          "Transactions"
        ],
        "summary": "VoidTransaction",
        "operationId": "VoidTransaction",
        "description": "Cancels a transaction that was created with the [Charge](#endpoint-charge)\nendpoint with a `delay_capture` value of `true`.\n\nSee [Delayed capture transactions](/articles/delayed-capture-transactions/)\nfor more information.",
        "x-oauthpermissions": [
          "PAYMENTS_WRITE"
        ],
        "security": [
          {
            "oauth2": [
              "PAYMENTS_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/locations/{location_id}/transactions/{transaction_id}": {
      "get": {
        "tags": [
          "Transactions"
        ],
        "summary": "RetrieveTransaction",
        "operationId": "RetrieveTransaction",
        "description": "Retrieves details for a single transaction.",
        "x-oauthpermissions": [
          "PAYMENTS_READ"
        ],
        "security": [
          {
            "oauth2": [
              "PAYMENTS_READ"
            ]
          }
        ]
      }
    },
    "/v2/locations/{location_id}/checkouts": {
      "post": {
        "tags": [
          "Checkout"
        ],
        "summary": "CreateCheckout",
        "operationId": "CreateCheckout",
        "description": "Creates a [Checkout](#type-checkout) response that links a\n`checkoutId` and `checkout_page_url` that customers can be directed to in\norder to provide their payment information using a payment processing\nworkflow hosted on connect.squareup.com.",
        "x-oauthpermissions": [
          "PAYMENTS_WRITE",
          "ORDERS_V2_WRITE"
        ],
        "security": [
          {
            "oauth2": [
              "PAYMENTS_WRITE",
              "ORDERS_V2_WRITE"
            ]
          }
        ]
      }
    },
    "/v1/me": {
      "get": {
        "tags": [
          "V1Locations"
        ],
        "summary": "Get a business\u0027s information.",
        "operationId": "RetrieveBusiness",
        "description": "Get a business\u0027s information.",
        "security": [
          {
            "oauth2": [
              "MERCHANT_PROFILE_READ"
            ]
          }
        ],
        "deprecated": true
      }
    },
    "/v1/me/locations": {
      "get": {
        "tags": [
          "V1Locations"
        ],
        "summary": "Provides details for a business\u0027s locations, including their IDs.",
        "operationId": "ListLocations",
        "description": "Provides details for a business\u0027s locations, including their IDs.",
        "security": [
          {
            "oauth2": [
              "MERCHANT_PROFILE_READ"
            ]
          }
        ],
        "deprecated": true
      }
    },
    "/v1/me/employees": {
      "post": {
        "tags": [
          "V1Employees"
        ],
        "summary": "Creates an employee for a business.",
        "operationId": "CreateEmployee",
        "description": "Creates an employee for a business.",
        "security": [
          {
            "oauth2": [
              "EMPLOYEES_WRITE"
            ]
          }
        ],
        "deprecated": false
      },
      "get": {
        "tags": [
          "V1Employees"
        ],
        "summary": "Provides summary information for all of a business\u0027s employees.",
        "operationId": "ListEmployees",
        "description": "Provides summary information for all of a business\u0027s employees.",
        "security": [
          {
            "oauth2": [
              "EMPLOYEES_READ"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/v1/me/employees/{employee_id}": {
      "get": {
        "tags": [
          "V1Employees"
        ],
        "summary": "Provides the details for a single employee.",
        "operationId": "RetrieveEmployee",
        "description": "Provides the details for a single employee.",
        "security": [
          {
            "oauth2": [
              "EMPLOYEES_READ"
            ]
          }
        ],
        "deprecated": false
      },
      "put": {
        "tags": [
          "V1Employees"
        ],
        "summary": "V1 UpdateEmployee",
        "operationId": "UpdateEmployee",
        "security": [
          {
            "oauth2": [
              "EMPLOYEES_WRITE"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/v1/me/roles": {
      "post": {
        "tags": [
          "V1Employees"
        ],
        "summary": "Creates an employee role you can then assign to employees.",
        "operationId": "CreateEmployeeRole",
        "description": "Creates an employee role you can then assign to employees.",
        "security": [
          {
            "oauth2": [
              "EMPLOYEES_WRITE"
            ]
          }
        ],
        "deprecated": false
      },
      "get": {
        "tags": [
          "V1Employees"
        ],
        "summary": "Provides summary information for all of a business\u0027s employee roles.",
        "operationId": "ListEmployeeRoles",
        "description": "Provides summary information for all of a business\u0027s employee roles.",
        "security": [
          {
            "oauth2": [
              "EMPLOYEES_READ"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/v1/me/roles/{role_id}": {
      "get": {
        "tags": [
          "V1Employees"
        ],
        "summary": "Provides the details for a single employee role.",
        "operationId": "RetrieveEmployeeRole",
        "description": "Provides the details for a single employee role.",
        "security": [
          {
            "oauth2": [
              "EMPLOYEES_READ"
            ]
          }
        ],
        "deprecated": false
      },
      "put": {
        "tags": [
          "V1Employees"
        ],
        "summary": "Modifies the details of an employee role.",
        "operationId": "UpdateEmployeeRole",
        "description": "Modifies the details of an employee role.",
        "security": [
          {
            "oauth2": [
              "EMPLOYEES_WRITE"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/v1/me/timecards": {
      "post": {
        "tags": [
          "V1Employees"
        ],
        "summary": "Creates a timecard for an employee. Each timecard corresponds to a single shift.",
        "operationId": "CreateTimecard",
        "description": "Creates a timecard for an employee. Each timecard corresponds to a single shift.",
        "security": [
          {
            "oauth2": [
              "TIMECARDS_WRITE"
            ]
          }
        ],
        "deprecated": false
      },
      "get": {
        "tags": [
          "V1Employees"
        ],
        "summary": "Provides summary information for all of a business\u0027s employee timecards.",
        "operationId": "ListTimecards",
        "description": "Provides summary information for all of a business\u0027s employee timecards.",
        "security": [
          {
            "oauth2": [
              "TIMECARDS_READ"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/v1/me/timecards/{timecard_id}": {
      "get": {
        "tags": [
          "V1Employees"
        ],
        "summary": "Provides the details for a single timecard.",
        "operationId": "RetrieveTimecard",
        "description": "Provides the details for a single timecard.",
        "security": [
          {
            "oauth2": [
              "TIMECARDS_READ"
            ]
          }
        ],
        "deprecated": false
      },
      "put": {
        "tags": [
          "V1Employees"
        ],
        "summary": "Modifies a timecard\u0027s details. This creates an API_EDIT event for the timecard. You can view a timecard\u0027s event history with the List Timecard Events endpoint.",
        "operationId": "UpdateTimecard",
        "description": "Modifies a timecard\u0027s details. This creates an API_EDIT event for the timecard. You can view a timecard\u0027s event history with the List Timecard Events endpoint.",
        "security": [
          {
            "oauth2": [
              "TIMECARDS_WRITE"
            ]
          }
        ],
        "deprecated": false
      },
      "delete": {
        "tags": [
          "V1Employees"
        ],
        "summary": "Deletes a timecard. Deleted timecards are still accessible from Connect API endpoints, but the value of their deleted field is set to true. See Handling deleted timecards for more information.",
        "operationId": "DeleteTimecard",
        "description": "Deletes a timecard. Deleted timecards are still accessible from Connect API endpoints, but the value of their deleted field is set to true. See Handling deleted timecards for more information.",
        "security": [
          {
            "oauth2": [
              "TIMECARDS_WRITE"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/v1/me/timecards/{timecard_id}/events": {
      "get": {
        "tags": [
          "V1Employees"
        ],
        "summary": "Provides summary information for all events associated with a particular timecard.",
        "operationId": "ListTimecardEvents",
        "description": "Provides summary information for all events associated with a particular timecard.",
        "security": [
          {
            "oauth2": [
              "TIMECARDS_READ"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/v1/{location_id}/cash-drawer-shifts": {
      "get": {
        "tags": [
          "V1Employees"
        ],
        "summary": "Provides the details for all of a location\u0027s cash drawer shifts during a date range. The date range you specify cannot exceed 90 days.",
        "operationId": "ListCashDrawerShifts",
        "description": "Provides the details for all of a location\u0027s cash drawer shifts during a date range. The date range you specify cannot exceed 90 days.",
        "security": [
          {
            "oauth2": [
              "PAYMENTS_READ"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/v1/{location_id}/cash-drawer-shifts/{shift_id}": {
      "get": {
        "tags": [
          "V1Employees"
        ],
        "summary": "Provides the details for a single cash drawer shift, including all events that occurred during the shift.",
        "operationId": "RetrieveCashDrawerShift",
        "description": "Provides the details for a single cash drawer shift, including all events that occurred during the shift.",
        "security": [
          {
            "oauth2": [
              "TIMECARDS_READ"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/v1/{location_id}/payments": {
      "get": {
        "tags": [
          "V1Transactions"
        ],
        "summary": "Provides summary information for all payments taken by a merchant or any of the merchant\u0027s mobile staff during a date range. Date ranges cannot exceed one year in length. See Date ranges for details of inclusive and exclusive dates.",
        "operationId": "ListPayments",
        "description": "Provides summary information for all payments taken by a merchant or any of the merchant\u0027s mobile staff during a date range. Date ranges cannot exceed one year in length. See Date ranges for details of inclusive and exclusive dates.",
        "security": [
          {
            "oauth2": [
              "PAYMENTS_READ"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/v1/{location_id}/payments/{payment_id}": {
      "get": {
        "tags": [
          "V1Transactions"
        ],
        "summary": "Provides comprehensive information for a single payment.",
        "operationId": "RetrievePayment",
        "description": "Provides comprehensive information for a single payment.",
        "security": [
          {
            "oauth2": [
              "PAYMENTS_READ"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/v1/{location_id}/settlements": {
      "get": {
        "tags": [
          "V1Transactions"
        ],
        "summary": "Provides summary information for all deposits and withdrawals initiated by Square to a merchant\u0027s bank account during a date range. Date ranges cannot exceed one year in length.",
        "operationId": "ListSettlements",
        "description": "Provides summary information for all deposits and withdrawals initiated by Square to a merchant\u0027s bank account during a date range. Date ranges cannot exceed one year in length. ",
        "security": [
          {
            "oauth2": [
              "SETTLEMENTS_READ"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/v1/{location_id}/settlements/{settlement_id}": {
      "get": {
        "tags": [
          "V1Transactions"
        ],
        "summary": "Provides comprehensive information for a single settlement, including the entries that contribute to the settlement\u0027s total.",
        "operationId": "RetrieveSettlement",
        "description": "Provides comprehensive information for a single settlement, including the entries that contribute to the settlement\u0027s total.",
        "security": [
          {
            "oauth2": [
              "SETTLEMENTS_READ"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/v1/{location_id}/refunds": {
      "get": {
        "tags": [
          "V1Transactions"
        ],
        "summary": "Provides the details for all refunds initiated by a merchant or any of the merchant\u0027s mobile staff during a date range. Date ranges cannot exceed one year in length.",
        "operationId": "ListRefunds",
        "description": "Provides the details for all refunds initiated by a merchant or any of the merchant\u0027s mobile staff during a date range. Date ranges cannot exceed one year in length.",
        "security": [
          {
            "oauth2": [
              "PAYMENTS_READ"
            ]
          }
        ],
        "deprecated": false
      },
      "post": {
        "tags": [
          "V1Transactions"
        ],
        "summary": "Issues a refund for a previously processed payment. You must issue a refund within 60 days of the associated payment.",
        "operationId": "CreateRefund",
        "description": "Issues a refund for a previously processed payment. You must issue a refund within 60 days of the associated payment.",
        "security": [
          {
            "oauth2": [
              "PAYMENTS_WRITE"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/v1/{location_id}/orders": {
      "get": {
        "tags": [
          "V1Transactions"
        ],
        "summary": "Provides summary information for a merchant\u0027s online store orders.",
        "operationId": "ListOrders",
        "description": "Provides summary information for a merchant\u0027s online store orders.",
        "security": [
          {
            "oauth2": [
              "ORDERS_READ"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/v1/{location_id}/orders/{order_id}": {
      "get": {
        "tags": [
          "V1Transactions"
        ],
        "summary": "Provides comprehensive information for a single online store order, including the order\u0027s history.",
        "operationId": "RetrieveOrder",
        "description": "Provides comprehensive information for a single online store order, including the order\u0027s history.",
        "security": [
          {
            "oauth2": [
              "ORDERS_READ"
            ]
          }
        ],
        "deprecated": false
      },
      "put": {
        "tags": [
          "V1Transactions"
        ],
        "summary": "Updates the details of an online store order. Every update you perform on an order corresponds to one of three actions:",
        "operationId": "UpdateOrder",
        "description": "Updates the details of an online store order. Every update you perform on an order corresponds to one of three actions:",
        "security": [
          {
            "oauth2": [
              "ORDERS_WRITE"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/v1/{location_id}/bank-accounts": {
      "get": {
        "tags": [
          "V1Transactions"
        ],
        "summary": "Provides non-confidential details for all of a location\u0027s associated bank accounts. This endpoint does not provide full bank account numbers, and there is no way to obtain a full bank account number with the Connect API.",
        "operationId": "ListBankAccounts",
        "description": "Provides non-confidential details for all of a location\u0027s associated bank accounts. This endpoint does not provide full bank account numbers, and there is no way to obtain a full bank account number with the Connect API.",
        "security": [
          {
            "oauth2": [
              "BANK_ACCOUNTS_READ"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/v1/{location_id}/bank-accounts/{bank_account_id}": {
      "get": {
        "tags": [
          "V1Transactions"
        ],
        "summary": "Provides non-confidential details for a merchant\u0027s associated bank account. This endpoint does not provide full bank account numbers, and there is no way to obtain a full bank account number with the Connect API.",
        "operationId": "RetrieveBankAccount",
        "description": "Provides non-confidential details for a merchant\u0027s associated bank account. This endpoint does not provide full bank account numbers, and there is no way to obtain a full bank account number with the Connect API.",
        "security": [
          {
            "oauth2": [
              "BANK_ACCOUNTS_READ"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/v1/{location_id}/items": {
      "post": {
        "tags": [
          "V1Items"
        ],
        "summary": "Creates an item and at least one variation for it.",
        "operationId": "CreateItem",
        "description": "Creates an item and at least one variation for it.",
        "security": [
          {
            "oauth2": [
              "ITEMS_WRITE"
            ]
          }
        ],
        "deprecated": false
      },
      "get": {
        "tags": [
          "V1Items"
        ],
        "summary": "Provides summary information for all of a location\u0027s items.",
        "operationId": "ListItems",
        "description": "Provides summary information for all of a location\u0027s items.",
        "security": [
          {
            "oauth2": [
              "ITEMS_READ"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/v1/{location_id}/items/{item_id}": {
      "get": {
        "tags": [
          "V1Items"
        ],
        "summary": "Provides the details for a single item, including associated modifier lists and fees.",
        "operationId": "RetrieveItem",
        "description": "Provides the details for a single item, including associated modifier lists and fees.",
        "security": [
          {
            "oauth2": [
              "ITEMS_READ"
            ]
          }
        ],
        "deprecated": false
      },
      "put": {
        "tags": [
          "V1Items"
        ],
        "summary": "Modifies the core details of an existing item.",
        "operationId": "UpdateItem",
        "description": "Modifies the core details of an existing item.",
        "security": [
          {
            "oauth2": [
              "ITEMS_WRITE"
            ]
          }
        ],
        "deprecated": false
      },
      "delete": {
        "tags": [
          "V1Items"
        ],
        "summary": "Deletes an existing item and all item variations associated with it.",
        "operationId": "DeleteItem",
        "description": "Deletes an existing item and all item variations associated with it.",
        "security": [
          {
            "oauth2": [
              "ITEMS_WRITE"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/v1/{location_id}/items/{item_id}/variations": {
      "post": {
        "tags": [
          "V1Items"
        ],
        "summary": "Creates an item variation for an existing item.",
        "operationId": "CreateVariation",
        "description": "Creates an item variation for an existing item.",
        "security": [
          {
            "oauth2": [
              "ITEMS_WRITE"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/v1/{location_id}/items/{item_id}/variations/{variation_id}": {
      "put": {
        "tags": [
          "V1Items"
        ],
        "summary": "Modifies the details of an existing item variation.",
        "operationId": "UpdateVariation",
        "description": "Modifies the details of an existing item variation.",
        "security": [
          {
            "oauth2": [
              "ITEMS_WRITE"
            ]
          }
        ],
        "deprecated": false
      },
      "delete": {
        "tags": [
          "V1Items"
        ],
        "summary": "Deletes an existing item variation from an item.",
        "operationId": "DeleteVariation",
        "description": "Deletes an existing item variation from an item.",
        "security": [
          {
            "oauth2": [
              "ITEMS_WRITE"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/v1/{location_id}/inventory": {
      "get": {
        "tags": [
          "V1Items"
        ],
        "summary": "Provides inventory information for all of a merchant\u0027s inventory-enabled item variations.",
        "operationId": "ListInventory",
        "description": "Provides inventory information for all of a merchant\u0027s inventory-enabled item variations.",
        "security": [
          {
            "oauth2": [
              "ITEMS_READ"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/v1/{location_id}/inventory/{variation_id}": {
      "post": {
        "tags": [
          "V1Items"
        ],
        "summary": "Adjusts an item variation\u0027s current available inventory.",
        "operationId": "AdjustInventory",
        "description": "Adjusts an item variation\u0027s current available inventory.",
        "security": [
          {
            "oauth2": [
              "ITEMS_WRITE"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/v1/{location_id}/modifier-lists": {
      "post": {
        "tags": [
          "V1Items"
        ],
        "summary": "Creates an item modifier list and at least one modifier option for it.",
        "operationId": "CreateModifierList",
        "description": "Creates an item modifier list and at least one modifier option for it.",
        "security": [
          {
            "oauth2": [
              "ITEMS_WRITE"
            ]
          }
        ],
        "deprecated": false
      },
      "get": {
        "tags": [
          "V1Items"
        ],
        "summary": "Lists all of a location\u0027s modifier lists.",
        "operationId": "ListModifierLists",
        "description": "Lists all of a location\u0027s modifier lists.",
        "security": [
          {
            "oauth2": [
              "ITEMS_READ"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/v1/{location_id}/modifier-lists/{modifier_list_id}": {
      "get": {
        "tags": [
          "V1Items"
        ],
        "summary": "Provides the details for a single modifier list.",
        "operationId": "RetrieveModifierList",
        "description": "Provides the details for a single modifier list.",
        "security": [
          {
            "oauth2": [
              "ITEMS_READ"
            ]
          }
        ],
        "deprecated": false
      },
      "put": {
        "tags": [
          "V1Items"
        ],
        "summary": "Modifies the details of an existing item modifier list.",
        "operationId": "UpdateModifierList",
        "description": "Modifies the details of an existing item modifier list.",
        "security": [
          {
            "oauth2": [
              "ITEMS_WRITE"
            ]
          }
        ],
        "deprecated": false
      },
      "delete": {
        "tags": [
          "V1Items"
        ],
        "summary": "Deletes an existing item modifier list and all modifier options associated with it.",
        "operationId": "DeleteModifierList",
        "description": "Deletes an existing item modifier list and all modifier options associated with it.",
        "security": [
          {
            "oauth2": [
              "ITEMS_WRITE"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/v1/{location_id}/items/{item_id}/modifier-lists/{modifier_list_id}": {
      "put": {
        "tags": [
          "V1Items"
        ],
        "summary": "Associates a modifier list with an item, meaning modifier options from the list can be applied to the item.",
        "operationId": "ApplyModifierList",
        "description": "Associates a modifier list with an item, meaning modifier options from the list can be applied to the item.",
        "security": [
          {
            "oauth2": [
              "ITEMS_WRITE"
            ]
          }
        ],
        "deprecated": false
      },
      "delete": {
        "tags": [
          "V1Items"
        ],
        "summary": "Removes a modifier list association from an item, meaning modifier options from the list can no longer be applied to the item.",
        "operationId": "RemoveModifierList",
        "description": "Removes a modifier list association from an item, meaning modifier options from the list can no longer be applied to the item.",
        "security": [
          {
            "oauth2": [
              "ITEMS_WRITE"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/v1/{location_id}/modifier-lists/{modifier_list_id}/modifier-options": {
      "post": {
        "tags": [
          "V1Items"
        ],
        "summary": "Creates an item modifier option and adds it to a modifier list.",
        "operationId": "CreateModifierOption",
        "description": "Creates an item modifier option and adds it to a modifier list.",
        "security": [
          {
            "oauth2": [
              "ITEMS_WRITE"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/v1/{location_id}/modifier-lists/{modifier_list_id}/modifier-options/{modifier_option_id}": {
      "put": {
        "tags": [
          "V1Items"
        ],
        "summary": "Modifies the details of an existing item modifier option.",
        "operationId": "UpdateModifierOption",
        "description": "Modifies the details of an existing item modifier option.",
        "security": [
          {
            "oauth2": [
              "ITEMS_WRITE"
            ]
          }
        ],
        "deprecated": false
      },
      "delete": {
        "tags": [
          "V1Items"
        ],
        "summary": "Deletes an existing item modifier option from a modifier list.",
        "operationId": "DeleteModifierOption",
        "description": "Deletes an existing item modifier option from a modifier list.",
        "security": [
          {
            "oauth2": [
              "ITEMS_WRITE"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/v1/{location_id}/categories": {
      "post": {
        "tags": [
          "V1Items"
        ],
        "summary": "Creates an item category.",
        "operationId": "CreateCategory",
        "description": "Creates an item category.",
        "security": [
          {
            "oauth2": [
              "ITEMS_WRITE"
            ]
          }
        ],
        "deprecated": false
      },
      "get": {
        "tags": [
          "V1Items"
        ],
        "summary": "Lists all of a location\u0027s item categories.",
        "operationId": "ListCategories",
        "description": "Lists all of a location\u0027s item categories.",
        "security": [
          {
            "oauth2": [
              "ITEMS_READ"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/v1/{location_id}/categories/{category_id}": {
      "put": {
        "tags": [
          "V1Items"
        ],
        "summary": "Modifies the details of an existing item category.",
        "operationId": "UpdateCategory",
        "description": "Modifies the details of an existing item category.",
        "security": [
          {
            "oauth2": [
              "ITEMS_WRITE"
            ]
          }
        ],
        "deprecated": false
      },
      "delete": {
        "tags": [
          "V1Items"
        ],
        "summary": "Deletes an existing item category.",
        "operationId": "DeleteCategory",
        "description": "Deletes an existing item category.",
        "security": [
          {
            "oauth2": [
              "ITEMS_WRITE"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/v1/{location_id}/discounts": {
      "post": {
        "tags": [
          "V1Items"
        ],
        "summary": "Creates a discount.",
        "operationId": "CreateDiscount",
        "description": "Creates a discount.",
        "security": [
          {
            "oauth2": [
              "ITEMS_WRITE"
            ]
          }
        ],
        "deprecated": false
      },
      "get": {
        "tags": [
          "V1Items"
        ],
        "summary": "Lists all of a location\u0027s discounts.",
        "operationId": "ListDiscounts",
        "description": "Lists all of a location\u0027s discounts.",
        "security": [
          {
            "oauth2": [
              "ITEMS_READ"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/v1/{location_id}/discounts/{discount_id}": {
      "put": {
        "tags": [
          "V1Items"
        ],
        "summary": "Modifies the details of an existing discount.",
        "operationId": "UpdateDiscount",
        "description": "Modifies the details of an existing discount.",
        "security": [
          {
            "oauth2": [
              "ITEMS_WRITE"
            ]
          }
        ],
        "deprecated": false
      },
      "delete": {
        "tags": [
          "V1Items"
        ],
        "summary": "Deletes an existing discount.",
        "operationId": "DeleteDiscount",
        "description": "Deletes an existing discount.",
        "security": [
          {
            "oauth2": [
              "ITEMS_WRITE"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/v1/{location_id}/fees": {
      "post": {
        "tags": [
          "V1Items"
        ],
        "summary": "Creates a fee (tax).",
        "operationId": "CreateFee",
        "description": "Creates a fee (tax).",
        "security": [
          {
            "oauth2": [
              "ITEMS_WRITE"
            ]
          }
        ],
        "deprecated": false
      },
      "get": {
        "tags": [
          "V1Items"
        ],
        "summary": "Lists all of a location\u0027s fees (taxes).",
        "operationId": "ListFees",
        "description": "Lists all of a location\u0027s fees (taxes).",
        "security": [
          {
            "oauth2": [
              "ITEMS_READ"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/v1/{location_id}/fees/{fee_id}": {
      "put": {
        "tags": [
          "V1Items"
        ],
        "summary": "Modifies the details of an existing fee (tax).",
        "operationId": "UpdateFee",
        "description": "Modifies the details of an existing fee (tax).",
        "security": [
          {
            "oauth2": [
              "ITEMS_WRITE"
            ]
          }
        ],
        "deprecated": false
      },
      "delete": {
        "tags": [
          "V1Items"
        ],
        "summary": "Deletes an existing fee (tax).",
        "operationId": "DeleteFee",
        "description": "Deletes an existing fee (tax).",
        "security": [
          {
            "oauth2": [
              "ITEMS_WRITE"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/v1/{location_id}/items/{item_id}/fees/{fee_id}": {
      "put": {
        "tags": [
          "V1Items"
        ],
        "summary": "Associates a fee with an item, meaning the fee is automatically applied to the item in Square Register.",
        "operationId": "ApplyFee",
        "description": "Associates a fee with an item, meaning the fee is automatically applied to the item in Square Register.",
        "security": [
          {
            "oauth2": [
              "ITEMS_WRITE"
            ]
          }
        ],
        "deprecated": false
      },
      "delete": {
        "tags": [
          "V1Items"
        ],
        "summary": "Removes a fee assocation from an item, meaning the fee is no longer automatically applied to the item in Square Register.",
        "operationId": "RemoveFee",
        "description": "Removes a fee assocation from an item, meaning the fee is no longer automatically applied to the item in Square Register.",
        "security": [
          {
            "oauth2": [
              "ITEMS_WRITE"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/v1/{location_id}/pages": {
      "post": {
        "tags": [
          "V1Items"
        ],
        "summary": "Creates a Favorites page in Square Register.",
        "operationId": "CreatePage",
        "description": "Creates a Favorites page in Square Register.",
        "security": [
          {
            "oauth2": [
              "ITEMS_WRITE"
            ]
          }
        ],
        "deprecated": false
      },
      "get": {
        "tags": [
          "V1Items"
        ],
        "summary": "Lists all of a location\u0027s Favorites pages in Square Register.",
        "operationId": "ListPages",
        "description": "Lists all of a location\u0027s Favorites pages in Square Register.",
        "security": [
          {
            "oauth2": [
              "ITEMS_READ"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/v1/{location_id}/pages/{page_id}": {
      "put": {
        "tags": [
          "V1Items"
        ],
        "summary": "Modifies the details of a Favorites page in Square Register.",
        "operationId": "UpdatePage",
        "description": "Modifies the details of a Favorites page in Square Register.",
        "security": [
          {
            "oauth2": [
              "ITEMS_WRITE"
            ]
          }
        ],
        "deprecated": false
      },
      "delete": {
        "tags": [
          "V1Items"
        ],
        "summary": "Deletes an existing Favorites page and all of its cells.",
        "operationId": "DeletePage",
        "description": "Deletes an existing Favorites page and all of its cells.",
        "security": [
          {
            "oauth2": [
              "ITEMS_WRITE"
            ]
          }
        ],
        "deprecated": false
      }
    },
    "/v1/{location_id}/pages/{page_id}/cells": {
      "put": {
        "tags": [
          "V1Items"
        ],
        "summary": "Modifies a cell of a Favorites page in Square Register.",
        "operationId": "UpdatePageCell",
        "description": "Modifies a cell of a Favorites page in Square Register.",
        "security": [
          {
            "oauth2": [
              "ITEMS_WRITE"
            ]
          }
        ],
        "deprecated": false
      },
      "delete": {
        "tags": [
          "V1Items"
        ],
        "summary": "Deletes a cell from a Favorites page in Square Register.",
        "operationId": "DeletePageCell",
        "description": "Deletes a cell from a Favorites page in Square Register.",
        "security": [
          {
            "oauth2": [
              "ITEMS_WRITE"
            ]
          }
        ],
        "deprecated": false
      }
    }
  }
}
