{
    "swagger": "2.0",
    "info": {
        "version": "3.0",
        "title": "Square Connect API",
        "description": "Client library for accessing the Square Connect APIs",
        "termsOfService": "https://connect.squareup.com/tos",
        "contact": {
            "name": "Square Developer Platform",
            "email": "developers@squareup.com",
            "url": "https://squareup.com/developers"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        }
    },
    "host": "connect.squareup.com",
    "schemes": [
        "https"
    ],
    "securityDefinitions": {
        "personal_access_token": {
            "type": "apiKey",
            "description": "Access token for accessing a single Square Account",
            "name": "Authorization",
            "in": "header"
        },
        "oauth2": {
            "type": "oauth2",
            "authorizationUrl": "https://connect.squareup.com/oauth2/authorize?<PARAMETERS>",
            "flow": "accessCode",
            "tokenUrl": "https://connect.squareup.com/oauth2/token",
            "scopes": {
                "MERCHANT_PROFILE_READ": "GET endpoints related to a merchant's business and location entities. Almost all Connect API applications need this permission in order to obtain a merchant's location IDs.",
                "PAYMENTS_READ": "GET endpoints related to transactions and refunds.",
                "PAYMENTS_WRITE": " POST, PUT, and DELETE endpoints related to transactions and refunds. E-commerce applications must request this permission.",
                "CUSTOMERS_READ": " GET endpoints related to customer management.",
                "CUSTOMERS_WRITE": "POST, PUT, and DELETE endpoints related to customer management.",
                "SETTLEMENTS_READ": "GET endpoints related to settlements (deposits).",
                "BANK_ACCOUNTS_READ": "GET endpoints related to a merchant's bank accounts.",
                "ITEMS_READ": "GET endpoints related to a merchant's item library.",
                "ITEMS_WRITE": "POST, PUT, and DELETE endpoints related to a merchant's item library.",
                "ORDERS_READ": "GET endpoints related to a merchant's Square online store.",
                "ORDERS_WRITE": "POST, PUT, and DELETE endpoints related to a merchant's Square online store.",
                "EMPLOYEES_READ": "GET endpoints related to employee management.",
                "EMPLOYEES_WRITE": "POST, PUT, and DELETE endpoints related to employee management.",
                "TIMECARDS_READ": "GET endpoints related to employee timecards.",
                "TIMECARDS_WRITE": "POST, PUT, and DELETE endpoints related to employee timecards."
            }
        }
    },
    "paths": {
        "/oauth2/token": {
            "post": {
                "tags": [
                    "OAuth"
                ],
                "summary": "Exchange an Authorization code for an Access Token ",
                "operationId": "GetAccessToken",
                "description": "Exchange an Authorization code for an Access Token ",
                "security": [],
                "deprecated": true
            }
        },
        "/oauth2/clients/{application_id}/access-token/renew": {
            "post": {
                "tags": [
                    "OAuth"
                ],
                "summary": "Renew your Access Token.",
                "operationId": "RenewToken",
                "description": "Renew your Access Token.",
                "security": [],
                "deprecated": true
            }
        },
        "/v1/me": {
            "get": {
                "tags": [
                    "v1BusinessManagement"
                ],
                "summary": "Get a business's information.",
                "operationId": "v1RetrieveBusiness",
                "description": "Get a business's information.",
                "security": [{
                    "personal_access_token": [],
                    "oauth2": ["MERCHANT_PROFILE_READ"]
                }],
                "deprecated": true
            }
        },
        "/v1/me/locations": {
            "get": {
                "tags": [
                    "v1BusinessManagement"
                ],
                "summary": "Provides details for a business's locations, including their IDs.",
                "operationId": "v1ListLocations",
                "description": "Provides details for a business's locations, including their IDs.",
                "security": [{
                    "personal_access_token": [],
                    "oauth2": ["MERCHANT_PROFILE_READ"]
                }],
                "deprecated": true
            }
        },
        "/v1/me/employees": {
            "post": {
                "tags": [
                    "Employees"
                ],
                "summary": "Creates an employee for a business.",
                "operationId": "CreateEmployee",
                "description": "Creates an employee for a business.",
                "security": [{
                    "personal_access_token": [],
                    "oauth2": ["EMPLOYEES_WRITE"]
                }],
                "deprecated": false
            },
            "get": {
                "tags": [
                    "Employees"
                ],
                "summary": "Provides summary information for all of a business's employees.",
                "operationId": "ListEmployees",
                "description": "Provides summary information for all of a business's employees.",
                "security": [{
                    "personal_access_token": [],
                    "oauth2": ["EMPLOYEES_READ"]
                }],
                "deprecated": false
            }
        },
        "/v1/me/employees/{employee_id}": {
            "get": {
                "tags": [
                    "Employees"
                ],
                "summary": "Provides the details for a single employee.",
                "operationId": "RetrieveEmployee",
                "description": "Provides the details for a single employee.",
                "security": [{
                    "personal_access_token": [],
                    "oauth2": ["EMPLOYEES_READ"]
                }],
                "deprecated": false
            },
            "put": {
                "tags": [
                    "Employees"
                ],
                "summary": "v1UpdateEmployee",
                "operationId": "UpdateEmployee",
                "security": [{
                    "personal_access_token": [],
                    "oauth2": ["EMPLOYEES_WRITE"]
                }],
                "deprecated": false
            }
        },
        "/v1/me/roles": {
            "post": {
                "tags": [
                    "Employees"
                ],
                "summary": "Creates an employee role you can then assign to employees.",
                "operationId": "CreateRole",
                "description": "Creates an employee role you can then assign to employees.",
                "security": [{
                    "personal_access_token": [],
                    "oauth2": ["EMPLOYEES_WRITE"]
                }],
                "deprecated": false
            },
            "get": {
                "tags": [
                    "Employees"
                ],
                "summary": "Provides summary information for all of a business's employee roles.",
                "operationId": "ListRoles",
                "description": "Provides summary information for all of a business's employee roles.",
                "security": [{
                    "personal_access_token": [],
                    "oauth2": ["EMPLOYEES_READ"]
                }],
                "deprecated": false
            }
        },
        "/v1/me/roles/{role_id}": {
            "get": {
                "tags": [
                    "Employees"
                ],
                "summary": "Provides the details for a single employee role.",
                "operationId": "RetrieveRole",
                "description": "Provides the details for a single employee role.",
                "security": [{
                    "personal_access_token": [],
                    "oauth2": ["EMPLOYEES_READ"]
                }],
                "deprecated": false
            },
            "put": {
                "tags": [
                    "Employees"
                ],
                "summary": "Modifies the details of an employee role.",
                "operationId": "UpdateRole",
                "description": "Modifies the details of an employee role.",
                "security": [{
                    "personal_access_token": [],
                    "oauth2": ["EMPLOYEES_WRITE"]
                }],
                "deprecated": false
            }
        },
        "/v1/me/timecards": {
            "post": {
                "tags": [
                    "Employees"
                ],
                "summary": "Creates a timecard for an employee. Each timecard corresponds to a single shift.",
                "operationId": "CreateTimecard",
                "description": "Creates a timecard for an employee. Each timecard corresponds to a single shift.",
                "security": [{
                    "personal_access_token": [],
                    "oauth2": ["TIMECARDS_WRITE"]
                }],
                "deprecated": false
            },
            "get": {
                "tags": [
                    "Employees"
                ],
                "summary": "Provides summary information for all of a business's employee timecards.",
                "operationId": "ListTimecards",
                "description": "Provides summary information for all of a business's employee timecards.",
                "security": [{
                    "personal_access_token": [],
                    "oauth2": ["TIMECARDS_READ"]
                }],
                "deprecated": false
            }
        },
        "/v1/me/timecards/{timecard_id}": {
            "get": {
                "tags": [
                    "Employees"
                ],
                "summary": "Provides the details for a single timecard.",
                "operationId": "RetrieveTimecard",
                "description": "Provides the details for a single timecard.",
                "security": [{
                    "personal_access_token": [],
                    "oauth2": ["TIMECARDS_READ"]
                }],
                "deprecated": false
            },
            "put": {
                "tags": [
                    "Employees"
                ],
                "summary": "Modifies a timecard's details. This creates an API_EDIT event for the timecard. You can view a timecard's event history with the List Timecard Events endpoint.",
                "operationId": "UpdateTimecard",
                "description": "Modifies a timecard's details. This creates an API_EDIT event for the timecard. You can view a timecard's event history with the List Timecard Events endpoint.",
                "security": [{
                    "personal_access_token": [],
                    "oauth2": ["TIMECARDS_WRITE"]
                }],
                "deprecated": false
            },
            "delete": {
                "tags": [
                    "Employees"
                ],
                "summary": "Deletes a timecard. Deleted timecards are still accessible from Connect API endpoints, but the value of their deleted field is set to true. See Handling deleted timecards for more information.",
                "operationId": "DeleteTimecard",
                "description": "Deletes a timecard. Deleted timecards are still accessible from Connect API endpoints, but the value of their deleted field is set to true. See Handling deleted timecards for more information.",
                "security": [{
                    "personal_access_token": [],
                    "oauth2": ["TIMECARDS_WRITE"]
                }],
                "deprecated": false
            }
        },
        "/v1/me/timecards/{timecard_id}/events": {
            "get": {
                "tags": [
                    "Employees"
                ],
                "summary": "Provides summary information for all events associated with a particular timecard.",
                "operationId": "ListTimecardEvents",
                "description": "Provides summary information for all events associated with a particular timecard.",
                "security": [{
                    "personal_access_token": [],
                    "oauth2": ["TIMECARDS_READ"]
                }],
                "deprecated": false
            }
        },
        "/v1/{location_id}/cash-drawer-shifts": {
            "get": {
                "tags": [
                    "Employees"
                ],
                "summary": "Provides the details for all of a location's cash drawer shifts during a date range. The date range you specify cannot exceed 90 days.",
                "operationId": "ListCashDrawerShifts",
                "description": "Provides the details for all of a location's cash drawer shifts during a date range. The date range you specify cannot exceed 90 days.",
                "security": [{
                    "personal_access_token": [],
                    "oauth2": ["PAYMENTS_READ"]
                }],
                "deprecated": false
            }
        },
        "/v1/{location_id}/cash-drawer-shifts/{shift_id}": {
            "get": {
                "tags": [
                    "Employees"
                ],
                "summary": "Provides the details for a single cash drawer shift, including all events that occurred during the shift.",
                "operationId": "RetrieveCashDrawerShift",
                "description": "Provides the details for a single cash drawer shift, including all events that occurred during the shift.",
                "security": [{
                    "personal_access_token": [],
                    "oauth2": ["TIMECARDS_READ"]
                }],
                "deprecated": false
            }
        },
        "/v1/{location_id}/payments": {
            "get": {
                "tags": [
                    "v1Transactions"
                ],
                "summary": "Provides summary information for all payments taken by a merchant or any of the merchant's mobile staff during a date range. Date ranges cannot exceed one year in length. See Date ranges for details of inclusive and exclusive dates.",
                "operationId": "v1ListPayments",
                "description": "Provides summary information for all payments taken by a merchant or any of the merchant's mobile staff during a date range. Date ranges cannot exceed one year in length. See Date ranges for details of inclusive and exclusive dates.",
                "security": [{
                    "personal_access_token": [],
                    "oauth2": ["PAYMENTS_READ"]
                }],
                "deprecated": false
            }
        },
        "/v1/{location_id}/payments/{payment_id}": {
            "get": {
                "tags": [
                    "v1Transactions"
                ],
                "summary": "Provides comprehensive information for a single payment.",
                "operationId": "v1RetrievePayment",
                "description": "Provides comprehensive information for a single payment.",
                "security": [{
                    "personal_access_token": [],
                    "oauth2": ["PAYMENTS_READ"]
                }],
                "deprecated": false
            }
        },
        "/v1/{location_id}/settlements": {
            "get": {
                "tags": [
                    "v1Transactions"
                ],
                "summary": "Provides summary information for all deposits and withdrawals initiated by Square to a merchant's bank account during a date range. Date ranges cannot exceed one year in length. ",
                "operationId": "v1ListSettlements",
                "description": "Provides summary information for all deposits and withdrawals initiated by Square to a merchant's bank account during a date range. Date ranges cannot exceed one year in length. ",
                "security": [{
                    "personal_access_token": [],
                    "oauth2": ["SETTLEMENTS_READ"]
                }],
                "deprecated": false
            }
        },
        "/v1/{location_id}/settlements/{settlement_id}": {
            "get": {
                "tags": [
                    "v1Transactions"
                ],
                "summary": "Provides comprehensive information for a single settlement, including the entries that contribute to the settlement's total.",
                "operationId": "v1RetrieveSettlement",
                "description": "Provides comprehensive information for a single settlement, including the entries that contribute to the settlement's total.",
                "security": [{
                    "personal_access_token": [],
                    "oauth2": ["SETTLEMENTS_READ"]
                }],
                "deprecated": false
            }
        },
        "/v1/{location_id}/refunds": {
            "get": {
                "tags": [
                    "v1Transactions"
                ],
                "summary": "Provides the details for all refunds initiated by a merchant or any of the merchant's mobile staff during a date range. Date ranges cannot exceed one year in length.",
                "operationId": "v1ListRefunds",
                "description": "Provides the details for all refunds initiated by a merchant or any of the merchant's mobile staff during a date range. Date ranges cannot exceed one year in length.",
                "security": [{
                    "personal_access_token": [],
                    "oauth2": ["PAYMENTS_READ"]
                }],
                "deprecated": false
            },
            "post": {
                "tags": [
                    "v1Transactions"
                ],
                "summary": "Issues a refund for a previously processed payment. You must issue a refund within 60 days of the associated payment.",
                "operationId": "v1CreateRefund",
                "description": "Issues a refund for a previously processed payment. You must issue a refund within 60 days of the associated payment.",
                "security": [{
                    "personal_access_token": [],
                    "oauth2": ["PAYMENTS_WRITE"]
                }],
                "deprecated": false
            }
        },
        "/v1/{location_id}/orders": {
            "get": {
                "tags": [
                    "v1Transactions"
                ],
                "summary": "Provides summary information for a merchant's online store orders.",
                "operationId": "v1ListOrders",
                "description": "Provides summary information for a merchant's online store orders.",
                "security": [{
                    "personal_access_token": [],
                    "oauth2": ["ORDERS_READ"]
                }],
                "deprecated": false
            }
        },
        "/v1/{location_id}/orders/{order_id}": {
            "get": {
                "tags": [
                    "v1Transactions"
                ],
                "summary": "Provides comprehensive information for a single online store order, including the order's history.",
                "operationId": "v1RetrieveOrder",
                "description": "Provides comprehensive information for a single online store order, including the order's history.",
                "security": [{
                    "personal_access_token": [],
                    "oauth2": ["ORDERS_READ"]
                }],
                "deprecated": false
            },
            "put": {
                "tags": [
                    "v1Transactions"
                ],
                "summary": "Updates the details of an online store order. Every update you perform on an order corresponds to one of three actions:",
                "operationId": "v1UpdateOrder",
                "description": "Updates the details of an online store order. Every update you perform on an order corresponds to one of three actions:",
                "security": [{
                    "personal_access_token": [],
                    "oauth2": ["ORDERS_WRITE"]
                }],
                "deprecated": false
            }
        },
        "/v1/{location_id}/bank-accounts": {
            "get": {
                "tags": [
                    "v1Transactions"
                ],
                "summary": "Provides non-confidential details for all of a location's associated bank accounts. This endpoint does not provide full bank account numbers, and there is no way to obtain a full bank account number with the Connect API.",
                "operationId": "v1ListBankAccounts",
                "description": "Provides non-confidential details for all of a location's associated bank accounts. This endpoint does not provide full bank account numbers, and there is no way to obtain a full bank account number with the Connect API.",
                "security": [{
                    "personal_access_token": [],
                    "oauth2": ["BANK_ACCOUNTS_READ"]
                }],
                "deprecated": false
            }
        },
        "/v1/{location_id}/bank-accounts/{bank_account_id}": {
            "get": {
                "tags": [
                    "v1Transactions"
                ],
                "summary": "Provides non-confidential details for a merchant's associated bank account. This endpoint does not provide full bank account numbers, and there is no way to obtain a full bank account number with the Connect API.",
                "operationId": "v1RetrieveBankAccount",
                "description": "Provides non-confidential details for a merchant's associated bank account. This endpoint does not provide full bank account numbers, and there is no way to obtain a full bank account number with the Connect API.",
                "security": [{
                    "personal_access_token": [],
                    "oauth2": ["BANK_ACCOUNTS_READ"]
                }],
                "deprecated": false
            }
        },
        "/v1/{location_id}/items": {
            "post": {
                "tags": [
                    "v1Items"
                ],
                "summary": "Creates an item and at least one variation for it.",
                "operationId": "v1CreateItem",
                "description": "Creates an item and at least one variation for it.",
                "security": [{
                    "personal_access_token": [],
                    "oauth2": ["ITEMS_WRITE"]
                }],
                "deprecated": false
            },
            "get": {
                "tags": [
                    "v1Items"
                ],
                "summary": "Provides summary information for all of a location's items.",
                "operationId": "v1ListItems",
                "description": "Provides summary information for all of a location's items.",
                "security": [{
                    "personal_access_token": [],
                    "oauth2": ["ITEMS_READ"]
                }],
                "deprecated": false
            }
        },
        "/v1/{location_id}/items/{item_id}": {
            "get": {
                "tags": [
                    "v1Items"
                ],
                "summary": "Provides the details for a single item, including associated modifier lists and fees.",
                "operationId": "v1RetrieveItem",
                "description": "Provides the details for a single item, including associated modifier lists and fees.",
                "security": [{
                    "personal_access_token": [],
                    "oauth2": ["ITEMS_READ"]
                }],
                "deprecated": false
            },
            "put": {
                "tags": [
                    "v1Items"
                ],
                "summary": "Modifies the core details of an existing item.",
                "operationId": "v1UpdateItem",
                "description": "Modifies the core details of an existing item.",
                "security": [{
                    "personal_access_token": [],
                    "oauth2": ["ITEMS_WRITE"]
                }],
                "deprecated": false
            },
            "delete": {
                "tags": [
                    "v1Items"
                ],
                "summary": "Deletes an existing item and all item variations associated with it.",
                "operationId": "v1DeleteItem",
                "description": "Deletes an existing item and all item variations associated with it.",
                "security": [{
                    "personal_access_token": [],
                    "oauth2": ["ITEMS_WRITE"]
                }],
                "deprecated": false
            }
        },
        "/v1/{location_id}/items/{item_id}/variations": {
            "post": {
                "tags": [
                    "v1Items"
                ],
                "summary": "Creates an item variation for an existing item.",
                "operationId": "v1CreateVariation",
                "description": "Creates an item variation for an existing item.",
                "security": [{
                    "personal_access_token": [],
                    "oauth2": ["ITEMS_WRITE"]
                }],
                "deprecated": false
            }
        },
        "/v1/{location_id}/items/{item_id}/variations/{variation_id}": {
            "put": {
                "tags": [
                    "v1Items"
                ],
                "summary": "Modifies the details of an existing item variation.",
                "operationId": "v1UpdateVaration",
                "description": "Modifies the details of an existing item variation.",
                "security": [{
                    "personal_access_token": [],
                    "oauth2": ["ITEMS_WRITE"]
                }],
                "deprecated": false
            },
            "delete": {
                "tags": [
                    "v1Items"
                ],
                "summary": "Deletes an existing item variation from an item.",
                "operationId": "v1DeleteVaration",
                "description": "Deletes an existing item variation from an item.",
                "security": [{
                    "personal_access_token": [],
                    "oauth2": ["ITEMS_WRITE"]
                }],
                "deprecated": false
            }
        },
        "/v1/{location_id}/inventory": {
            "get": {
                "tags": [
                    "v1Items"
                ],
                "summary": "Provides inventory information for all of a merchant's inventory-enabled item variations.",
                "operationId": "v1ListInventory",
                "description": "Provides inventory information for all of a merchant's inventory-enabled item variations.",
                "security": [{
                    "personal_access_token": [],
                    "oauth2": ["ITEMS_READ"]
                }],
                "deprecated": false
            }
        },
        "/v1/{location_id}/inventory/{variation_id}": {
            "post": {
                "tags": [
                    "v1Items"
                ],
                "summary": "Adjusts an item variation's current available inventory.",
                "operationId": "v1AdjustInventory",
                "description": "Adjusts an item variation's current available inventory.",
                "security": [{
                    "personal_access_token": [],
                    "oauth2": ["ITEMS_WRITE"]
                }],
                "deprecated": false
            }
        },
        "/v1/{location_id}/modifier-lists": {
            "post": {
                "tags": [
                    "v1Items"
                ],
                "summary": "Creates an item modifier list and at least one modifier option for it.",
                "operationId": "v1CreateModifierList",
                "description": "Creates an item modifier list and at least one modifier option for it.",
                "security": [{
                    "personal_access_token": [],
                    "oauth2": ["ITEMS_WRITE"]
                }],
                "deprecated": false
            },
            "get": {
                "tags": [
                    "v1Items"
                ],
                "summary": "Lists all of a location's modifier lists.",
                "operationId": "v1ListModifierLists",
                "description": "Lists all of a location's modifier lists.",
                "security": [{
                    "personal_access_token": [],
                    "oauth2": ["ITEMS_READ"]
                }],
                "deprecated": false
            }
        },
        "/v1/{location_id}/modifier-lists/{modifier_list_id}": {
            "get": {
                "tags": [
                    "v1Items"
                ],
                "summary": "Provides the details for a single modifier list.",
                "operationId": "v1RetrieveModiferList",
                "description": "Provides the details for a single modifier list.",
                "security": [{
                    "personal_access_token": [],
                    "oauth2": ["ITEMS_READ"]
                }],
                "deprecated": false
            },
            "put": {
                "tags": [
                    "v1Items"
                ],
                "summary": "Modifies the details of an existing item modifier list.",
                "operationId": "v1UpdateModifierList",
                "description": "Modifies the details of an existing item modifier list.",
                "security": [{
                    "personal_access_token": [],
                    "oauth2": ["ITEMS_WRITE"]
                }],
                "deprecated": false
            },
            "delete": {
                "tags": [
                    "v1Items"
                ],
                "summary": "Deletes an existing item modifier list and all modifier options associated with it.",
                "operationId": "v1DeleteModiferList",
                "description": "Deletes an existing item modifier list and all modifier options associated with it.",
                "security": [{
                    "personal_access_token": [],
                    "oauth2": ["ITEMS_WRITE"]
                }],
                "deprecated": false
            }
        },
        "/v1/{location_id}/items/{item_id}/modifier-lists/{modifier_list_id}": {
            "put": {
                "tags": [
                    "v1Items"
                ],
                "summary": "Associates a modifier list with an item, meaning modifier options from the list can be applied to the item.",
                "operationId": "v1ApplyModiferList",
                "description": "Associates a modifier list with an item, meaning modifier options from the list can be applied to the item.",
                "security": [{
                    "personal_access_token": [],
                    "oauth2": ["ITEMS_WRITE"]
                }],
                "deprecated": false
            },
            "delete": {
                "tags": [
                    "v1Items"
                ],
                "summary": "Removes a modifier list association from an item, meaning modifier options from the list can no longer be applied to the item.",
                "operationId": "v1RemoveModiferList",
                "description": "Removes a modifier list association from an item, meaning modifier options from the list can no longer be applied to the item.",
                "security": [{
                    "personal_access_token": [],
                    "oauth2": ["ITEMS_WRITE"]
                }],
                "deprecated": false
            }
        },
        "/v1/{location_id}/modifier-lists/{modifier_list_id}/modifier-options": {
            "post": {
                "tags": [
                    "v1Items"
                ],
                "summary": "Creates an item modifier option and adds it to a modifier list.",
                "operationId": "v1CreateModifierListOption",
                "description": "Creates an item modifier option and adds it to a modifier list.",
                "security": [{
                    "personal_access_token": [],
                    "oauth2": ["ITEMS_WRITE"]
                }],
                "deprecated": false
            }
        },
        "/v1/{location_id}/modifier-lists/{modifier_list_id}/modifier-options/{modifier_option_id}": {
            "put": {
                "tags": [
                    "v1Items"
                ],
                "summary": "Modifies the details of an existing item modifier option.",
                "operationId": "v1UpdateModifierListOption",
                "description": "Modifies the details of an existing item modifier option.",
                "security": [{
                    "personal_access_token": [],
                    "oauth2": ["ITEMS_WRITE"]
                }],
                "deprecated": false
            },
            "delete": {
                "tags": [
                    "v1Items"
                ],
                "summary": "Deletes an existing item modifier option from a modifier list.",
                "operationId": "v1DeleteModiferListOption",
                "description": "Deletes an existing item modifier option from a modifier list.",
                "security": [{
                    "personal_access_token": [],
                    "oauth2": ["ITEMS_WRITE"]
                }],
                "deprecated": false
            }
        },
        "/v1/{location_id}/categories": {
            "post": {
                "tags": [
                    "v1Items"
                ],
                "summary": "Creates an item category.",
                "operationId": "v1CreateCategory",
                "description": "Creates an item category.",
                "security": [{
                    "personal_access_token": [],
                    "oauth2": ["ITEMS_WRITE"]
                }],
                "deprecated": false
            },
            "get": {
                "tags": [
                    "v1Items"
                ],
                "summary": "Lists all of a location's item categories.",
                "operationId": "v1ListItemCategories",
                "description": "Lists all of a location's item categories.",
                "security": [{
                    "personal_access_token": [],
                    "oauth2": ["ITEMS_READ"]
                }],
                "deprecated": false
            }
        },
        "/v1/{location_id}/categories/{category_id}": {
            "put": {
                "tags": [
                    "v1Items"
                ],
                "summary": "Modifies the details of an existing item category.",
                "operationId": "v1UpdateItemCategory",
                "description": "Modifies the details of an existing item category.",
                "security": [{
                    "personal_access_token": [],
                    "oauth2": ["ITEMS_WRITE"]
                }],
                "deprecated": false
            },
            "delete": {
                "tags": [
                    "v1Items"
                ],
                "summary": "Deletes an existing item category.",
                "operationId": "v1DeleteItemCategory",
                "description": "Deletes an existing item category.",
                "security": [{
                    "personal_access_token": [],
                    "oauth2": ["ITEMS_WRITE"]
                }],
                "deprecated": false
            }
        },
        "/v1/{location_id}/discounts": {
            "post": {
                "tags": [
                    "v1Items"
                ],
                "summary": "Creates a discount.",
                "operationId": "v1CreateDiscount",
                "description": "Creates a discount.",
                "security": [{
                    "personal_access_token": [],
                    "oauth2": ["ITEMS_WRITE"]
                }],
                "deprecated": false
            },
            "get": {
                "tags": [
                    "v1Items"
                ],
                "summary": "Lists all of a location's discounts.",
                "operationId": "v1ListDiscounts",
                "description": "Lists all of a location's discounts.",
                "security": [{
                    "personal_access_token": [],
                    "oauth2": ["ITEMS_READ"]
                }],
                "deprecated": false
            }
        },
        "/v1/{location_id}/discounts/{discount_id}": {
            "put": {
                "tags": [
                    "v1Items"
                ],
                "summary": "Modifies the details of an existing discount.",
                "operationId": "v1UpdateItemDiscount",
                "description": "Modifies the details of an existing discount.",
                "security": [{
                    "personal_access_token": [],
                    "oauth2": ["ITEMS_WRITE"]
                }],
                "deprecated": false
            },
            "delete": {
                "tags": [
                    "v1Items"
                ],
                "summary": "Deletes an existing discount.",
                "operationId": "v1DeleteItemDiscount",
                "description": "Deletes an existing discount.",
                "security": [{
                    "personal_access_token": [],
                    "oauth2": ["ITEMS_WRITE"]
                }],
                "deprecated": false
            }
        },
        "/v1/{location_id}/fees": {
            "post": {
                "tags": [
                    "v1Items"
                ],
                "summary": "Creates a fee (tax).",
                "operationId": "v1CreateFee",
                "description": "Creates a fee (tax).",
                "security": [{
                    "personal_access_token": [],
                    "oauth2": ["ITEMS_WRITE"]
                }],
                "deprecated": false
            },
            "get": {
                "tags": [
                    "v1Items"
                ],
                "summary": "Lists all of a location's fees (taxes).",
                "operationId": "v1ListFees",
                "description": "Lists all of a location's fees (taxes).",
                "security": [{
                    "personal_access_token": [],
                    "oauth2": ["ITEMS_READ"]
                }],
                "deprecated": false
            }
        },
        "/v1/{location_id}/fees/{fee_id}": {
            "put": {
                "tags": [
                    "v1Items"
                ],
                "summary": "Modifies the details of an existing fee (tax).",
                "operationId": "v1UpdateFee",
                "description": "Modifies the details of an existing fee (tax).",
                "security": [{
                    "personal_access_token": [],
                    "oauth2": ["ITEMS_WRITE"]
                }],
                "deprecated": false
            },
            "delete": {
                "tags": [
                    "v1Items"
                ],
                "summary": "Deletes an existing fee (tax).",
                "operationId": "v1DeleteFee",
                "description": "Deletes an existing fee (tax).",
                "security": [{
                    "personal_access_token": [],
                    "oauth2": ["ITEMS_WRITE"]
                }],
                "deprecated": false
            }
        },
        "/v1/{location_id}/items/{item_id}/fees/{fee_id}": {
            "put": {
                "tags": [
                    "v1Items"
                ],
                "summary": "Associates a fee with an item, meaning the fee is automatically applied to the item in Square Register.",
                "operationId": "v1ApplyFee",
                "description": "Associates a fee with an item, meaning the fee is automatically applied to the item in Square Register.",
                "security": [{
                    "personal_access_token": [],
                    "oauth2": ["ITEMS_WRITE"]
                }],
                "deprecated": false
            },
            "delete": {
                "tags": [
                    "v1Items"
                ],
                "summary": "Removes a fee assocation from an item, meaning the fee is no longer automatically applied to the item in Square Register.",
                "operationId": "v1RemoveFee",
                "description": "Removes a fee assocation from an item, meaning the fee is no longer automatically applied to the item in Square Register.",
                "security": [{
                    "personal_access_token": [],
                    "oauth2": ["ITEMS_WRITE"]
                }],
                "deprecated": false
            }
        },
        "/v1/{location_id}/pages": {
            "post": {
                "tags": [
                    "v1Items"
                ],
                "summary": "Creates a Favorites page in Square Register.",
                "operationId": "v1CreatePage",
                "description": "Creates a Favorites page in Square Register.",
                "security": [{
                    "personal_access_token": [],
                    "oauth2": ["ITEMS_WRITE"]
                }],
                "deprecated": false
            },
            "get": {
                "tags": [
                    "v1Items"
                ],
                "summary": "Lists all of a location's Favorites pages in Square Register.",
                "operationId": "v1ListPages",
                "description": "Lists all of a location's Favorites pages in Square Register.",
                "security": [{
                    "personal_access_token": [],
                    "oauth2": ["ITEMS_READ"]
                }],
                "deprecated": false
            }
        },
        "/v1/{location_id}/pages/{page_id}": {
            "put": {
                "tags": [
                    "v1Items"
                ],
                "summary": "Modifies the details of a Favorites page in Square Register.",
                "operationId": "v1UpdatePage",
                "description": "Modifies the details of a Favorites page in Square Register.",
                "security": [{
                    "personal_access_token": [],
                    "oauth2": ["ITEMS_WRITE"]
                }],
                "deprecated": false
            },
            "delete": {
                "tags": [
                    "v1Items"
                ],
                "summary": "Deletes an existing Favorites page and all of its cells.",
                "operationId": "v1DeletePage",
                "description": "Deletes an existing Favorites page and all of its cells.",
                "security": [{
                    "personal_access_token": [],
                    "oauth2": ["ITEMS_WRITE"]
                }],
                "deprecated": false
            }
        },
        "/v1/{location_id}/pages/{page_id}/cells": {
            "put": {
                "tags": [
                    "v1Items"
                ],
                "summary": "Modifies a cell of a Favorites page in Square Register.",
                "operationId": "v1UpdatePageCell",
                "description": "Modifies a cell of a Favorites page in Square Register.",
                "security": [{
                    "personal_access_token": [],
                    "oauth2": ["ITEMS_WRITE"]
                }],
                "deprecated": false
            },
            "delete": {
                "tags": [
                    "v1Items"
                ],
                "summary": "Deletes a cell from a Favorites page in Square Register.",
                "operationId": "v1DeletePageCell",
                "description": "Deletes a cell from a Favorites page in Square Register.",
                "security": [{
                    "personal_access_token": [],
                    "oauth2": ["ITEMS_WRITE"]
                }],
                "deprecated": false
            }
        },
        "/v2/locations/{location_id}/transactions": {
            "post": {
                "tags": [
                    "Transaction"
                ],
                "summary": "Charge",
                "operationId": "Charge",
                "description": "Charges a card represented by a token.",
                "security": [{
                    "personal_access_token": [],
                    "oauth2": ["PAYMENTS_WRITE"]
                }],
                "deprecated": false
            },
            "get": {
                "tags": [
                    "Transaction"
                ],
                "summary": "ListTransactions",
                "operationId": "ListTransactions",
                "description": "Lists transactions for a particular location.\n\nWhen making a request to this endpoint, your request body **must** include either the `cursor` parameter, or it must\ninclude both `begin_time` and `end_time` with an optional `sort_order`.",
                "security": [{
                    "personal_access_token": [],
                    "oauth2": ["PAYMENTS_READ"]
                }],
                "deprecated": false
            }
        },
        "/v2/locations/{location_id}/transactions/{transaction_id}/refund": {
            "post": {
                "tags": [
                    "Refund"
                ],
                "summary": "CreateRefund",
                "operationId": "CreateRefund",
                "description": "Initiates a refund for a previously charged tender.",
                "security": [{
                    "personal_access_token": [],
                    "oauth2": ["PAYMENTS_WRITE"]
                }],
                "deprecated": false
            }
        },
        "/v2/locations/{location_id}/refunds": {
            "get": {
                "tags": [
                    "Refund"
                ],
                "summary": "ListRefunds",
                "operationId": "ListRefunds",
                "description": "Lists refunds for one of a business\u0027s locations.",
                "security": [{
                    "personal_access_token": [],
                    "oauth2": ["PAYMENTS_READ"]
                }],
                "deprecated": false
            }
        },
        "/v2/locations": {
            "get": {
                "tags": [
                    "Location"
                ],
                "summary": "ListLocations",
                "operationId": "ListLocations",
                "description": "Provides summary information for all of a business\u0027s locations.",
                "security": [{
                    "personal_access_token": [],
                    "oauth2": ["MERCHANT_PROFILE_READ"]
                }],
                "deprecated": false
            }
        },
        "/v2/customers": {
            "post": {
                "tags": [
                    "Customer"
                ],
                "summary": "CreateCustomer",
                "operationId": "CreateCustomer",
                "description": "Creates a new customer for the business, which can have associated cards on file.",
                "security": [{
                    "personal_access_token": [],
                    "oauth2": ["CUSTOMERS_WRITE"]
                }],
                "deprecated": false
            },
            "get": {
                "tags": [
                    "Customer"
                ],
                "summary": "ListCustomers",
                "operationId": "ListCustomers",
                "description": "Lists a business\u0027s customers.",
                "security": [{
                    "personal_access_token": [],
                    "oauth2": ["CUSTOMERS_READ"]
                }],
                "deprecated": false
            }
        },
        "/v2/customers/{customer_id}": {
            "put": {
                "tags": [
                    "Customer"
                ],
                "summary": "UpdateCustomer",
                "operationId": "UpdateCustomer",
                "description": "Updates the details of an existing customer.",
                "security": [{
                    "personal_access_token": [],
                    "oauth2": ["CUSTOMERS_WRITE"]
                }],
                "deprecated": false
            },
            "get": {
                "tags": [
                    "Customer"
                ],
                "summary": "RetrieveCustomer",
                "operationId": "RetrieveCustomer",
                "description": "Returns details for a single customer.",
                "security": [{
                    "personal_access_token": [],
                    "oauth2": ["CUSTOMERS_READ"]
                }],
                "deprecated": false
            },
            "delete": {
                "tags": [
                    "Customer"
                ],
                "summary": "DeleteCustomer",
                "operationId": "DeleteCustomer",
                "description": "Deletes a customer from a business.",
                "security": [{
                    "personal_access_token": [],
                    "oauth2": ["CUSTOMERS_WRITE"]
                }],
                "deprecated": false
            }
        },
        "/v2/customers/{customer_id}/cards": {
            "post": {
                "tags": [
                    "Customer.Card"
                ],
                "summary": "CreateCustomerCard",
                "operationId": "CreateCustomerCard",
                "description": "Adds a card on file to an existing customer.",
                "security": [{
                    "personal_access_token": [],
                    "oauth2": ["CUSTOMERS_WRITE"]
                }],
                "deprecated": false
            }
        },
        "/v2/customers/{customer_id}/cards/{card_id}": {
            "delete": {
                "tags": [
                    "Customer.Card"
                ],
                "summary": "DeleteCustomerCard",
                "operationId": "DeleteCustomerCard",
                "description": "Removes a card on file from a customer.",
                "security": [{
                    "personal_access_token": [],
                    "oauth2": ["CUSTOMERS_WRITE"]
                }],
                "deprecated": false
            }
        },
        "/v2/locations/{location_id}/transactions/{transaction_id}/capture": {
            "post": {
                "tags": [
                    "Transaction"
                ],
                "summary": "CaptureTransaction",
                "operationId": "CaptureTransaction",
                "description": "Captures a transaction that was created with the **Charge**\nendpoint with a `delay_capture` value of `true`.",
                "security": [{
                    "personal_access_token": [],
                    "oauth2": ["PAYMENTS_WRITE"]
                }],
                "deprecated": false
            }
        },
        "/v2/locations/{location_id}/transactions/{transaction_id}/void": {
            "post": {
                "tags": [
                    "Transaction"
                ],
                "summary": "VoidTransaction",
                "operationId": "VoidTransaction",
                "description": "Cancels a transaction that was created with the **Charge**\nendpoint with a `delay_capture` value of `true`.",
                "security": [{
                    "personal_access_token": [],
                    "oauth2": ["PAYMENTS_WRITE"]
                }],
                "deprecated": false
            }
        },
        "/v2/locations/{location_id}/transactions/{transaction_id}": {
            "get": {
                "tags": [
                    "Transaction"
                ],
                "summary": "RetrieveTransaction",
                "operationId": "RetrieveTransaction",
                "description": "Retrieves details for a single transaction.",
                "security": [{
                    "personal_access_token": [],
                    "oauth2": ["PAYMENTS_READ"]
                }],
                "deprecated": false
            }
        }
    }
}
